/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-11 02:55:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import datatypes.DtActividadDeportivaExt;

public final class homeDesktop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("datatypes.DtActividadDeportivaExt");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/template/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("   <div class=\"container-fluid mt-4\">\r\n");
      out.write("     <div class=\"row mb-5 mx-3 mx-md-5\">\r\n");
      out.write("       <div style=\"background:url(");
      out.print(request.getContextPath());
      out.write("/assets/images/misc/wallpaperBg.jpg) center\" class=\"bienvenida p-5\">\r\n");
      out.write("         <div class=\"texto-bienvenida\">\r\n");
      out.write("           <h1>¡Bienvenido a Entrenamos.uy!</h1>\r\n");
      out.write("           <p>\r\n");
      out.write("             ¡Es hora de moverse! Entrenamos.uy es la plataforma definitiva para hacer ejercicio sin moverse. Vea actividades deportivas,  compre cuponeras e inscribase a clases\r\n");
      out.write("             sin tener que despegarse de su pantalla. Gracias a nuestras instituciones afilidadas que proveen profesores experimentados,  usted puede recibir la mejor experiencia\r\n");
      out.write("             deportiva que podría llegar a imaginarse. \r\n");
      out.write("           </p>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("     <div class=\"row mx-3 mx-md-5\">\r\n");
      out.write("       <div class=\"ins-cat col-2\">\r\n");
      out.write("         ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/template/stdLeftSection.jsp", out, false);
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"actdep-panel col-7 ms-2 ms-sm-1 ms-md-0\">\r\n");
      out.write("           <h1 class=\"h2\">Noticias:</h1>\r\n");
      out.write("       	<br>\r\n");
      out.write("      		<div class=\"border border-dark row ms-1 mb-4 p-5 text-dark bg-light rounded-3 \">\r\n");
      out.write("      			<div id=\"carouselNoticias\" class=\"carousel carousel-dark slide\" data-ride=\"carousel\">\r\n");
      out.write("			  <div class=\"carousel-inner\">\r\n");
      out.write("			    <div class=\"row carousel-item active\">\r\n");
      out.write("			      	<div style=\"align-items: center;\" class=\"col\">\r\n");
      out.write("		        		<img style=\"margin-left: 13em; height: 16em;\" src=\"");
      out.print(request.getContextPath());
      out.write("/assets/images/misc/bones.gif\">\r\n");
      out.write("		        		<img style=\"margin-right: 10em; height: 16em;\" src=\"");
      out.print(request.getContextPath());
      out.write("/assets/images/misc/bones2.gif\">\r\n");
      out.write("		        	</div>\r\n");
      out.write("			        <div class=\"col\">\r\n");
      out.write("			        	<h2>A sacudir los huesos!</h2>\r\n");
      out.write("			          	<p>En entrenamos.uy tomamos todas las precauciones necesarias para que los huesos de nuestros clientes se mantengan sanos e integrales.\r\n");
      out.write("			         De ahora en adelante,  todas nuestras actividades deportivas son cuidadosamente analizadas y aprobadas como <b>Bone Safe</b>.</p>\r\n");
      out.write("			        </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			    <div class=\"carousel-item\">\r\n");
      out.write("			    	<div class=\"col\">\r\n");
      out.write("		        		<img style=\"height: 16em; display: block; margin-left: auto; margin-right: auto;\" src=\"");
      out.print(request.getContextPath());
      out.write("/assets/images/misc/empleadoMes.png\">\r\n");
      out.write("		        	</div>\r\n");
      out.write("			        <div class=\"col\">\r\n");
      out.write("			        	<h2>Profesor del mes: <b>Viktor</b></h2>\r\n");
      out.write("			          	<p>El equipo directivo de entrenamos.uy con gran placer felicita a <b>Viktor</b> por su larga trayectoria en el sitio.\r\n");
      out.write("			          	 Proveniente de Moscow,  Viktor vino a Uruguay a enseñar como levantar unas buenas pesas. Este no conoce los límites,  y esto mismo\r\n");
      out.write("			          	 es lo que tanto motiva a sus estudiantes. Conozca más sobre este profesor\r\n");
      out.write("			          	 <a href=\"");
      out.print(request.getContextPath());
      out.write("/usuarios?nickname=viktor\" class=\"clase\">visitando su perfil.</a> </p>\r\n");
      out.write("			        </div>\r\n");
      out.write("			     </div>\r\n");
      out.write("			     <div class=\"carousel-item\">\r\n");
      out.write("			    	<h2 class=\"h2\">Actividades destacadas:</h2>\r\n");
      out.write("		        	<br>\r\n");
      out.write("		       		");
for (int i = 1; i < 4; i++) {
		       			DtActividadDeportivaExt datosActividad = (DtActividadDeportivaExt) request.getAttribute("actividad" + i);
		       			if (datosActividad != null) {
      out.write("\r\n");
      out.write("			        	<div class=\"actDep row mb-4\">\r\n");
      out.write("				            <img src=\"");
      out.print(request.getContextPath());
      out.write("/api/content?c=act&id=");
      out.print(datosActividad.getNombre());
      out.write("\" class=\"img-fluid d-inline col-5 col-md-7\">\r\n");
      out.write("				            <p class=\"d-inline col-12 col-sm-9 col-md-7 text-start\"><b>");
      out.print(datosActividad.getNombre());
      out.write(".</b> ");
      out.print(datosActividad.getDescripcion());
      out.write("\r\n");
      out.write("				            <a href=\"");
      out.print(request.getContextPath());
      out.write("/actividades?actividad=");
      out.print(datosActividad.getNombre());
      out.write("\" class=\"text-primary\">Leer mas.</a></p>\r\n");
      out.write("			          	</div>\r\n");
      out.write("			    	");
  }
			    	}
      out.write("\r\n");
      out.write("			     </div>\r\n");
      out.write("			  </div>\r\n");
      out.write("				  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselNoticias\" data-bs-slide=\"prev\">\r\n");
      out.write("				    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("				  </button>\r\n");
      out.write("				  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselNoticias\" data-bs-slide=\"next\">\r\n");
      out.write("				    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("				  </button>\r\n");
      out.write("			</div>\r\n");
      out.write("       	</div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"col-3 ps-1 ps-sm-2\">\r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/template/stdRightSection.jsp", out, false);
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write(" 	</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/template/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
