/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-11 02:56:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import datatypes.DtClaseExt;
import datatypes.DtActividadDeportivaExt;
import datatypes.DtUsuarioExt;
import datatypes.DtSocioExt;
import datatypes.DtFecha;

public final class searchMobile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("datatypes.DtFecha");
    _jspx_imports_classes.add("datatypes.DtUsuarioExt");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("datatypes.DtActividadDeportivaExt");
    _jspx_imports_classes.add("datatypes.DtSocioExt");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("datatypes.DtClaseExt");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/template/headerMobile.jsp", out, false);
      out.write("\r\n");
      out.write("    ");
DtUsuarioExt loggedUser = (DtUsuarioExt) request.getSession().getAttribute("loggedUser");
    if ((loggedUser != null) && (loggedUser instanceof DtSocioExt)) {
      out.write("\r\n");
      out.write("    <div id=\"section-socio\" class=\"row mt-4 mb-3\">\r\n");
      out.write("	    <p class=\"bienvenida-socio mt-3\"><i class=\"fas fa-user-circle\"></i> Bienvenido <b>");
      out.print(loggedUser.getNickname());
      out.write("</b></p>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Comienzo Listado usuario -->		\r\n");
      out.write("	");
List<?> listaActividades = (List<?>)request.getAttribute("actividades");
	List<?> listaClases = (List<?>)request.getAttribute("clases");
	
	// Guarda el link para la nueva request de los formularios:
	String encabezado = new String();
	String link = request.getContextPath() + "/search?";
	if (request.getAttribute("actividades") != null) {
		link += "actividades=yes";
		encabezado = "Actividades Deportivas";
		if (request.getAttribute("clases") != null) {
			link += "&clases=yes";
			encabezado = "Clases";
		}
	
	// Auxiliares para el orden y filtro:
	String orden = (String) request.getAttribute("orden");
	Set<?> listaInstituciones = (Set<?>) request.getAttribute("instituciones");
	Set<?> listaCategorias = (Set<?>) request.getAttribute("categorias");
	Set<?> filtro = null;
	String linkAndFiltro = link;
	filtro = (Set<?>) request.getAttribute("filtroInsti");
	String nombreFltr = new String();
	if (filtro.size() > 0) {
		linkAndFiltro += "&fltrI1=" + (String)filtro.iterator().next();
		nombreFltr = "de Institucion " + (String)filtro.iterator().next();
	}
	filtro = (Set<?>) request.getAttribute("filtroCat");
	if (filtro.size() > 0) {
		linkAndFiltro += "&fltrC1=" + (String)filtro.iterator().next();
		nombreFltr = "de Categoria " + (String)filtro.iterator().next();
	} 
      out.write("\r\n");
      out.write("    <div id=\"section-verActsDeps\" class=\"row pt-4 pb-4\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <h1 id=\"title\">Ver ");
      out.print(encabezado);
      out.write("</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <div id=\"filtrarInstitucion\" class=\"row filtrar pt-3\">\r\n");
      out.write("            <div class=\"btn-group\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"fas fa-school\"></i> Instituciones\r\n");
      out.write("              </button>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("              	");
for (Object x : listaInstituciones) {
      out.write("\r\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"");
      out.print(link);
      out.write("&fltrI1=");
      out.print((String)x);
      out.write('"');
      out.write('>');
      out.print((String)x);
      out.write("</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"filtrarCategoria\" class=\"row filtrar pt-2 pb-4\">\r\n");
      out.write("          <div class=\"btn-group\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("              <i class=\"fas fa-align-justify\"></i> Categorias\r\n");
      out.write("            </button>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("            ");
for (Object x : listaCategorias) {
      out.write("\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"");
      out.print(link);
      out.write("&fltrC1=");
      out.print((String)x);
      out.write('"');
      out.write('>');
      out.print((String)x);
      out.write("</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
if (encabezado.equals("Clases")) { 
      out.write("\r\n");
      out.write("        <div id=\"filtrarActividades\" class=\"row filtrar pt-2 pb-4\">\r\n");
      out.write("        ");
if ((((Set<?>)request.getAttribute("filtroInsti")).size() > 0) || (((Set<?>)request.getAttribute("filtroCat")).size() > 0)) {
      out.write("\r\n");
      out.write("          <div class=\"btn-group\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("              <i class=\"fas fa-align-justify\"></i> Actividades Deportivas\r\n");
      out.write("            </button>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("            ");
for (Object obj : listaActividades) {
      out.write("\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"");
      out.print(linkAndFiltro);
      out.write("&fltrA=");
      out.print(((DtActividadDeportivaExt)obj).getNombre());
      out.write('"');
      out.write('>');
      out.print(((DtActividadDeportivaExt)obj).getNombre());
      out.write("</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("       	\r\n");
      out.write("        <div id=\"infoActDep\" class=\"row\">\r\n");
      out.write("        	");
 String textoInfo = nombreFltr;
        	String fltrAct = (String) request.getAttribute("filtroAct");
        	if (encabezado.equals("Clases") && (!fltrAct.isEmpty())) {
        		 textoInfo += " y Actividad " + fltrAct;
        	}
      out.write("\r\n");
      out.write("            <p><i class=\"fas fa-info-circle\"></i> Listado de ");
      out.print(encabezado);
      out.write(' ');
      out.print(textoInfo);
      out.write("</p>\r\n");
      out.write("            <p><i class=\"fas fa-info-circle\"></i> Presione una para ver mas informacion</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr style=\"width:88%; height: 2px;\">\r\n");
      out.write("        <div id=\"actsDeps\" class=\"row\">\r\n");
      out.write("        	");
if (encabezado.equals("Clases")) {
        		for (Object obj : listaClases) {
      out.write("\r\n");
      out.write("	            <a href=\"");
      out.print(request.getContextPath());
      out.write("/clases?clase=");
      out.print(((DtClaseExt)obj).getNombre());
      out.write("\">\r\n");
      out.write("	            <div class=\"row pt-2\">\r\n");
      out.write("	                <img class=\"imgSearchMobile\" src=\"");
      out.print(request.getContextPath());
      out.write("/api/content?c=cla&id=");
      out.print(((DtClaseExt)obj).getNombre());
      out.write("\" alt=\"");
      out.print(((DtClaseExt)obj).getNombre());
      out.write("\">\r\n");
      out.write("	            </div>\r\n");
      out.write("		        <div class=\"row pt-2 pb-2\">\r\n");
      out.write("	                <h3>");
      out.print(((DtClaseExt)obj).getNombre());
      out.write("</h3>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            </a>\r\n");
      out.write("            	");
 } 
      out.write("\r\n");
      out.write("            ");
 } else { 
            	for (Object obj : listaActividades) {
      out.write("\r\n");
      out.write("   	            <a href=\"");
      out.print(request.getContextPath());
      out.write("/actividades?actividad=");
      out.print(((DtActividadDeportivaExt)obj).getNombre());
      out.write("\">\r\n");
      out.write("   	            <div class=\"row pt-2\">\r\n");
      out.write("   	                <img class=\"imgSearchMobile\" src=\"");
      out.print(request.getContextPath());
      out.write("/api/content?c=act&id=");
      out.print(((DtActividadDeportivaExt)obj).getNombre());
      out.write("\" alt=\"");
      out.print(((DtActividadDeportivaExt)obj).getNombre());
      out.write("\">\r\n");
      out.write("   	            </div>\r\n");
      out.write("   		        <div class=\"row pt-2 pb-2\">\r\n");
      out.write("   	                <h3>");
      out.print(((DtActividadDeportivaExt)obj).getNombre());
      out.write("</h3>\r\n");
      out.write("   	            </div>\r\n");
      out.write("   	            </a>\r\n");
      out.write("               	");
 } 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"section-sponsors\" class=\"row pt-5 pb-5\">\r\n");
      out.write("    <div class=\"row text-center\">\r\n");
      out.write("        <h1>Sponsors</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row mt-4\">\r\n");
      out.write("        <div class=\"col-6 text-center\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/images/misc/logoPowerade.jpg\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-6 text-center\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/images/misc/logoGatorade.jpg\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row mt-4\">\r\n");
      out.write("        <div class=\"col-6 text-center\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/images/misc/logoUniversal.png\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-6 text-center\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/images/misc/logoAdidas.jpg\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/template/footerMobile.jsp", out, false);
      out.write('\r');
      out.write('\n');
 } //End If ActividadesDeportivas == yes (necesario para saber que se usaran las listas)
} //End If es DtSocioExt
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
