
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-09T16:09:53.055-03:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "ActividadDeportivaException", targetNamespace = "http://webServices/")
public class ActividadDeportivaException_Exception extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -1092062134822033469L;
	private webservices.ActividadDeportivaException actividadDeportivaException;

    public ActividadDeportivaException_Exception() {
        super();
    }
    
    public ActividadDeportivaException_Exception(String message) {
        super(message);
    }
    
    public ActividadDeportivaException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ActividadDeportivaException_Exception(String message, webservices.ActividadDeportivaException actividadDeportivaException) {
        super(message);
        this.actividadDeportivaException = actividadDeportivaException;
    }

    public ActividadDeportivaException_Exception(String message, webservices.ActividadDeportivaException actividadDeportivaException, Throwable cause) {
        super(message, cause);
        this.actividadDeportivaException = actividadDeportivaException;
    }

    public webservices.ActividadDeportivaException getFaultInfo() {
        return this.actividadDeportivaException;
    }
}
