
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-06T19:16:01.835-03:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "ClaseException", targetNamespace = "http://webServices/")
public class ClaseException_Exception extends Exception {
    
    private webservices.ClaseException claseException;

    public ClaseException_Exception() {
        super();
    }
    
    public ClaseException_Exception(String message) {
        super(message);
    }
    
    public ClaseException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ClaseException_Exception(String message, webservices.ClaseException claseException) {
        super(message);
        this.claseException = claseException;
    }

    public ClaseException_Exception(String message, webservices.ClaseException claseException, Throwable cause) {
        super(message, cause);
        this.claseException = claseException;
    }

    public webservices.ClaseException getFaultInfo() {
        return this.claseException;
    }
}
