
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-09T11:33:16.460-03:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "CuponeraNoExisteException", targetNamespace = "http://webServices/")
public class CuponeraNoExisteException_Exception extends Exception {
    
    private webservices.CuponeraNoExisteException cuponeraNoExisteException;

    public CuponeraNoExisteException_Exception() {
        super();
    }
    
    public CuponeraNoExisteException_Exception(String message) {
        super(message);
    }
    
    public CuponeraNoExisteException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CuponeraNoExisteException_Exception(String message, webservices.CuponeraNoExisteException cuponeraNoExisteException) {
        super(message);
        this.cuponeraNoExisteException = cuponeraNoExisteException;
    }

    public CuponeraNoExisteException_Exception(String message, webservices.CuponeraNoExisteException cuponeraNoExisteException, Throwable cause) {
        super(message, cause);
        this.cuponeraNoExisteException = cuponeraNoExisteException;
    }

    public webservices.CuponeraNoExisteException getFaultInfo() {
        return this.cuponeraNoExisteException;
    }
}
