
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-06T19:16:01.851-03:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "FechaInvalidaException", targetNamespace = "http://webServices/")
public class FechaInvalidaException_Exception extends Exception {
    
    private webservices.FechaInvalidaException fechaInvalidaException;

    public FechaInvalidaException_Exception() {
        super();
    }
    
    public FechaInvalidaException_Exception(String message) {
        super(message);
    }
    
    public FechaInvalidaException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public FechaInvalidaException_Exception(String message, webservices.FechaInvalidaException fechaInvalidaException) {
        super(message);
        this.fechaInvalidaException = fechaInvalidaException;
    }

    public FechaInvalidaException_Exception(String message, webservices.FechaInvalidaException fechaInvalidaException, Throwable cause) {
        super(message, cause);
        this.fechaInvalidaException = fechaInvalidaException;
    }

    public webservices.FechaInvalidaException getFaultInfo() {
        return this.fechaInvalidaException;
    }
}
