
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-09T16:09:53.063-03:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "InstitucionException", targetNamespace = "http://webServices/")
public class InstitucionException_Exception extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 5981272061086712438L;
	private webservices.InstitucionException institucionException;

    public InstitucionException_Exception() {
        super();
    }
    
    public InstitucionException_Exception(String message) {
        super(message);
    }
    
    public InstitucionException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InstitucionException_Exception(String message, webservices.InstitucionException institucionException) {
        super(message);
        this.institucionException = institucionException;
    }

    public InstitucionException_Exception(String message, webservices.InstitucionException institucionException, Throwable cause) {
        super(message, cause);
        this.institucionException = institucionException;
    }

    public webservices.InstitucionException getFaultInfo() {
        return this.institucionException;
    }
}
