
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-11T02:21:58.167-03:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "IOException", targetNamespace = "http://webServices/")
public class IOException_Exception extends Exception {
    
    private webservices.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, webservices.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, webservices.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public webservices.IOException getFaultInfo() {
        return this.ioException;
    }
}
