
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-07T14:14:54.840-03:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "NoExisteCuponeraException", targetNamespace = "http://webServices/")
public class NoExisteCuponeraException_Exception extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -6032030257718408846L;
	private webservices.NoExisteCuponeraException noExisteCuponeraException;

    public NoExisteCuponeraException_Exception() {
        super();
    }
    
    public NoExisteCuponeraException_Exception(String message) {
        super(message);
    }
    
    public NoExisteCuponeraException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NoExisteCuponeraException_Exception(String message, webservices.NoExisteCuponeraException noExisteCuponeraException) {
        super(message);
        this.noExisteCuponeraException = noExisteCuponeraException;
    }

    public NoExisteCuponeraException_Exception(String message, webservices.NoExisteCuponeraException noExisteCuponeraException, Throwable cause) {
        super(message, cause);
        this.noExisteCuponeraException = noExisteCuponeraException;
    }

    public webservices.NoExisteCuponeraException getFaultInfo() {
        return this.noExisteCuponeraException;
    }
}
