
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-09T11:33:16.452-03:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "UsuarioNoExisteException", targetNamespace = "http://webServices/")
public class UsuarioNoExisteException_Exception extends Exception {
    
    private webservices.UsuarioNoExisteException usuarioNoExisteException;

    public UsuarioNoExisteException_Exception() {
        super();
    }
    
    public UsuarioNoExisteException_Exception(String message) {
        super(message);
    }
    
    public UsuarioNoExisteException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UsuarioNoExisteException_Exception(String message, webservices.UsuarioNoExisteException usuarioNoExisteException) {
        super(message);
        this.usuarioNoExisteException = usuarioNoExisteException;
    }

    public UsuarioNoExisteException_Exception(String message, webservices.UsuarioNoExisteException usuarioNoExisteException, Throwable cause) {
        super(message, cause);
        this.usuarioNoExisteException = usuarioNoExisteException;
    }

    public webservices.UsuarioNoExisteException getFaultInfo() {
        return this.usuarioNoExisteException;
    }
}
