
package webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-06T19:15:26.436-03:00
 * Generated source version: 2.7.9
 * 
 */
public final class WSActividadController_WSActividadControllerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webServices/", "WSActividadControllerService");

    private WSActividadController_WSActividadControllerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSActividadControllerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSActividadControllerService ss = new WSActividadControllerService(wsdlURL, SERVICE_NAME);
        WSActividadController port = ss.getWSActividadControllerPort();  
        
        {
        System.out.println("Invoking seleccionarClase...");
        java.lang.String _seleccionarClase_arg0 = "_seleccionarClase_arg01905088662";
        java.lang.String _seleccionarClase_arg1 = "_seleccionarClase_arg1-1360866461";
        java.lang.String _seleccionarClase_arg2 = "_seleccionarClase_arg2501623364";
        try {
            webservices.DtClaseWS _seleccionarClase__return = port.seleccionarClase(_seleccionarClase_arg0, _seleccionarClase_arg1, _seleccionarClase_arg2);
            System.out.println("seleccionarClase.result=" + _seleccionarClase__return);

        } catch (ActividadDeportivaException_Exception e) { 
            System.out.println("Expected exception: ActividadDeportivaException has occurred.");
            System.out.println(e.toString());
        } catch (ClaseException_Exception e) { 
            System.out.println("Expected exception: ClaseException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerCategorias...");
        net.java.dev.jaxb.array.StringArray _obtenerCategorias__return = port.obtenerCategorias();
        System.out.println("obtenerCategorias.result=" + _obtenerCategorias__return);


        }
        {
        System.out.println("Invoking obtenerActividades...");
        java.lang.String _obtenerActividades_arg0 = "_obtenerActividades_arg01904233606";
        try {
            net.java.dev.jaxb.array.StringArray _obtenerActividades__return = port.obtenerActividades(_obtenerActividades_arg0);
            System.out.println("obtenerActividades.result=" + _obtenerActividades__return);

        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerActDepIngresadas...");
        net.java.dev.jaxb.array.StringArray _obtenerActDepIngresadas__return = port.obtenerActDepIngresadas();
        System.out.println("obtenerActDepIngresadas.result=" + _obtenerActDepIngresadas__return);


        }
        {
        System.out.println("Invoking obtenerDatosInstitucion...");
        java.lang.String _obtenerDatosInstitucion_arg0 = "_obtenerDatosInstitucion_arg01630647909";
        try {
            webservices.DtInstitucion _obtenerDatosInstitucion__return = port.obtenerDatosInstitucion(_obtenerDatosInstitucion_arg0);
            System.out.println("obtenerDatosInstitucion.result=" + _obtenerDatosInstitucion__return);

        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerDeltaInstituciones...");
        java.lang.String _obtenerDeltaInstituciones_arg0 = "_obtenerDeltaInstituciones_arg0-1304432980";
        java.lang.String _obtenerDeltaInstituciones_arg1 = "_obtenerDeltaInstituciones_arg11187064659";
        try {
            net.java.dev.jaxb.array.StringArray _obtenerDeltaInstituciones__return = port.obtenerDeltaInstituciones(_obtenerDeltaInstituciones_arg0, _obtenerDeltaInstituciones_arg1);
            System.out.println("obtenerDeltaInstituciones.result=" + _obtenerDeltaInstituciones__return);

        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getActDepExt...");
        java.lang.String _getActDepExt_arg0 = "_getActDepExt_arg0-653968590";
        java.lang.String _getActDepExt_arg1 = "_getActDepExt_arg1344981438";
        try {
            webservices.DtActividadWS _getActDepExt__return = port.getActDepExt(_getActDepExt_arg0, _getActDepExt_arg1);
            System.out.println("getActDepExt.result=" + _getActDepExt__return);

        } catch (ActividadDeportivaException_Exception e) { 
            System.out.println("Expected exception: ActividadDeportivaException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerSocios...");
        net.java.dev.jaxb.array.StringArray _obtenerSocios__return = port.obtenerSocios();
        System.out.println("obtenerSocios.result=" + _obtenerSocios__return);


        }
        {
        System.out.println("Invoking buscarActDep...");
        java.lang.String _buscarActDep_arg0 = "_buscarActDep_arg0120005762";
        try {
            webservices.DtActividadWS _buscarActDep__return = port.buscarActDep(_buscarActDep_arg0);
            System.out.println("buscarActDep.result=" + _buscarActDep__return);

        } catch (ActividadDeportivaException_Exception e) { 
            System.out.println("Expected exception: ActividadDeportivaException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerInstituciones...");
        net.java.dev.jaxb.array.StringArray _obtenerInstituciones__return = port.obtenerInstituciones();
        System.out.println("obtenerInstituciones.result=" + _obtenerInstituciones__return);


        }
        {
        System.out.println("Invoking finalizarActividad...");
        java.lang.String _finalizarActividad_arg0 = "_finalizarActividad_arg01771977110";
        port.finalizarActividad(_finalizarActividad_arg0);


        }
        {
        System.out.println("Invoking ingresarDatosActividadDep...");
        java.lang.String _ingresarDatosActividadDep_arg0 = "_ingresarDatosActividadDep_arg02044450925";
        webservices.DtActividadWS _ingresarDatosActividadDep_arg1 = new webservices.DtActividadWS();
        java.util.List<java.lang.String> _ingresarDatosActividadDep_arg1Clases = new java.util.ArrayList<java.lang.String>();
        java.lang.String _ingresarDatosActividadDep_arg1ClasesVal1 = "_ingresarDatosActividadDep_arg1ClasesVal-1424453816";
        _ingresarDatosActividadDep_arg1Clases.add(_ingresarDatosActividadDep_arg1ClasesVal1);
        _ingresarDatosActividadDep_arg1.getClases().addAll(_ingresarDatosActividadDep_arg1Clases);
        java.util.List<java.lang.String> _ingresarDatosActividadDep_arg1Cup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _ingresarDatosActividadDep_arg1CupVal1 = "_ingresarDatosActividadDep_arg1CupVal-461211538";
        _ingresarDatosActividadDep_arg1Cup.add(_ingresarDatosActividadDep_arg1CupVal1);
        _ingresarDatosActividadDep_arg1.getCup().addAll(_ingresarDatosActividadDep_arg1Cup);
        java.util.List<java.lang.String> _ingresarDatosActividadDep_arg1Categorias = new java.util.ArrayList<java.lang.String>();
        java.lang.String _ingresarDatosActividadDep_arg1CategoriasVal1 = "_ingresarDatosActividadDep_arg1CategoriasVal1138135427";
        _ingresarDatosActividadDep_arg1Categorias.add(_ingresarDatosActividadDep_arg1CategoriasVal1);
        _ingresarDatosActividadDep_arg1.getCategorias().addAll(_ingresarDatosActividadDep_arg1Categorias);
        _ingresarDatosActividadDep_arg1.setNombre("Nombre1511937763");
        _ingresarDatosActividadDep_arg1.setDescripcion("Descripcion1775721442");
        _ingresarDatosActividadDep_arg1.setCreador("Creador1580399465");
        _ingresarDatosActividadDep_arg1.setImgName("ImgName902346021");
        _ingresarDatosActividadDep_arg1.setDuracionMinutos(-604377593);
        _ingresarDatosActividadDep_arg1.setCosto(0.5764405f);
        webservices.DtFechaWS _ingresarDatosActividadDep_arg1FechaRegistro = new webservices.DtFechaWS();
        _ingresarDatosActividadDep_arg1FechaRegistro.setAnio(-2062653485);
        _ingresarDatosActividadDep_arg1FechaRegistro.setMes(417401596);
        _ingresarDatosActividadDep_arg1FechaRegistro.setDia(-800368345);
        _ingresarDatosActividadDep_arg1FechaRegistro.setHoras(1845745850);
        _ingresarDatosActividadDep_arg1FechaRegistro.setMinutos(-578418518);
        _ingresarDatosActividadDep_arg1FechaRegistro.setSegundos(-195885279);
        _ingresarDatosActividadDep_arg1.setFechaRegistro(_ingresarDatosActividadDep_arg1FechaRegistro);
        webservices.TEstadoWS _ingresarDatosActividadDep_arg1Estado = webservices.TEstadoWS.FINALIZADA;
        _ingresarDatosActividadDep_arg1.setEstado(_ingresarDatosActividadDep_arg1Estado);
        try {
            boolean _ingresarDatosActividadDep__return = port.ingresarDatosActividadDep(_ingresarDatosActividadDep_arg0, _ingresarDatosActividadDep_arg1);
            System.out.println("ingresarDatosActividadDep.result=" + _ingresarDatosActividadDep__return);

        } catch (ActividadDeportivaException_Exception e) { 
            System.out.println("Expected exception: ActividadDeportivaException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
