
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-09T16:09:53.067-03:00
 * Generated source version: 2.7.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSActividadControllerService",
                      portName = "WSActividadControllerPort",
                      targetNamespace = "http://webServices/",
                      wsdlLocation = "http://localhost:9129/entrenamosuy/actividadController?wsdl",
                      endpointInterface = "webservices.WSActividadController")
                      
public class WSActividadControllerImpl implements WSActividadController {

    private static final Logger LOG = Logger.getLogger(WSActividadControllerImpl.class.getName());

    /* (non-Javadoc)
     * @see webservices.WSActividadController#seleccionarClase(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public webservices.DtClaseWS seleccionarClase(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) throws ActividadDeportivaException_Exception , ClaseException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation seleccionarClase");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            webservices.DtClaseWS _return = new webservices.DtClaseWS();
            java.util.List<java.lang.String> _returnAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAlumnosVal1 = "_returnAlumnosVal-1477371320";
            _returnAlumnos.add(_returnAlumnosVal1);
            _return.getAlumnos().addAll(_returnAlumnos);
            java.util.List<java.lang.Integer> _returnCalificacionesData = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnCalificacionesDataVal1 = Integer.valueOf(-878144858);
            _returnCalificacionesData.add(_returnCalificacionesDataVal1);
            _return.getCalificacionesData().addAll(_returnCalificacionesData);
            java.util.List<java.lang.String> _returnCalificacionesHead = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCalificacionesHeadVal1 = "_returnCalificacionesHeadVal1204718673";
            _returnCalificacionesHead.add(_returnCalificacionesHeadVal1);
            _return.getCalificacionesHead().addAll(_returnCalificacionesHead);
            _return.setCorreoProfesor("CorreoProfesor612177703");
            webservices.DtFechaWS _returnFechaClase = new webservices.DtFechaWS();
            _returnFechaClase.setAnio(-794603229);
            _returnFechaClase.setMes(-1975827019);
            _returnFechaClase.setDia(1877695999);
            _returnFechaClase.setHoras(-1174869492);
            _returnFechaClase.setMinutos(-1907438887);
            _returnFechaClase.setSegundos(-2084491558);
            _return.setFechaClase(_returnFechaClase);
            webservices.DtFechaWS _returnFechaRegistro = new webservices.DtFechaWS();
            _returnFechaRegistro.setAnio(-1432074401);
            _returnFechaRegistro.setMes(-688652513);
            _returnFechaRegistro.setDia(685882027);
            _returnFechaRegistro.setHoras(-1738604352);
            _returnFechaRegistro.setMinutos(147215783);
            _returnFechaRegistro.setSegundos(-414068421);
            _return.setFechaRegistro(_returnFechaRegistro);
            _return.setImgName("ImgName-1569701725");
            _return.setMaxSocios(758524119);
            _return.setMinSocios(134514356);
            _return.setNicknameProfesor("NicknameProfesor337778127");
            _return.setNombre("Nombre-191068715");
            webservices.DtPremioWS _returnPremio = new webservices.DtPremioWS();
            _returnPremio.setDescripcion("Descripcion-506597309");
            _returnPremio.setCantidad(1027999972);
            webservices.DtFechaWS _returnPremioFechaSorteo = new webservices.DtFechaWS();
            _returnPremioFechaSorteo.setAnio(-1299658508);
            _returnPremioFechaSorteo.setMes(1051580647);
            _returnPremioFechaSorteo.setDia(-1254541289);
            _returnPremioFechaSorteo.setHoras(-1531046587);
            _returnPremioFechaSorteo.setMinutos(487745217);
            _returnPremioFechaSorteo.setSegundos(-1419866412);
            _returnPremio.setFechaSorteo(_returnPremioFechaSorteo);
            java.util.List<java.lang.String> _returnPremioGanadores = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnPremioGanadoresVal1 = "_returnPremioGanadoresVal56575170";
            _returnPremioGanadores.add(_returnPremioGanadoresVal1);
            _returnPremio.getGanadores().addAll(_returnPremioGanadores);
            _return.setPremio(_returnPremio);
            java.util.List<java.lang.String> _returnSoloNickAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnSoloNickAlumnosVal1 = "_returnSoloNickAlumnosVal128239598";
            _returnSoloNickAlumnos.add(_returnSoloNickAlumnosVal1);
            _return.getSoloNickAlumnos().addAll(_returnSoloNickAlumnos);
            _return.setUrlVideo("UrlVideo1241638366");
            _return.setUrlwebsite("Urlwebsite-677336084");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new ClaseException_Exception("ClaseException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#obtenerCategorias(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerCategorias() { 
        LOG.info("Executing operation obtenerCategorias");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1044466889";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#obtenerActividades(java.lang.String  arg0 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerActividades(java.lang.String arg0) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerActividades");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal49978029";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#obtenerActDepIngresadas(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerActDepIngresadas() { 
        LOG.info("Executing operation obtenerActDepIngresadas");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1813297321";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#obtenerDatosInstitucion(java.lang.String  arg0 )*
     */
    public webservices.DtInstitucionWS obtenerDatosInstitucion(java.lang.String arg0) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerDatosInstitucion");
        System.out.println(arg0);
        try {
            webservices.DtInstitucionWS _return = new webservices.DtInstitucionWS();
            _return.setNombre("Nombre-1995073250");
            _return.setDescripcion("Descripcion1048428214");
            _return.setUrl("Url1429628386");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#obtenerDeltaInstituciones(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerDeltaInstituciones(java.lang.String arg0,java.lang.String arg1) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerDeltaInstituciones");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1413034062";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#getActDepExt(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public webservices.DtActividadWS getActDepExt(java.lang.String arg0,java.lang.String arg1) throws ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation getActDepExt");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            webservices.DtActividadWS _return = new webservices.DtActividadWS();
            java.util.List<java.lang.String> _returnClases = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnClasesVal1 = "_returnClasesVal-67802759";
            _returnClases.add(_returnClasesVal1);
            _return.getClases().addAll(_returnClases);
            java.util.List<java.lang.String> _returnCup = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCupVal1 = "_returnCupVal-991071665";
            _returnCup.add(_returnCupVal1);
            _return.getCup().addAll(_returnCup);
            java.util.List<java.lang.String> _returnCategorias = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCategoriasVal1 = "_returnCategoriasVal-1135080534";
            _returnCategorias.add(_returnCategoriasVal1);
            _return.getCategorias().addAll(_returnCategorias);
            _return.setNombre("Nombre-371835581");
            _return.setDescripcion("Descripcion820409328");
            _return.setCreador("Creador205928715");
            _return.setImgName("ImgName-925355713");
            _return.setDuracionMinutos(511086525);
            _return.setCosto(0.64084274f);
            webservices.DtFechaWS _returnFechaRegistro = new webservices.DtFechaWS();
            _returnFechaRegistro.setAnio(-2005827135);
            _returnFechaRegistro.setMes(781167261);
            _returnFechaRegistro.setDia(1653486860);
            _returnFechaRegistro.setHoras(867249864);
            _returnFechaRegistro.setMinutos(-1862466654);
            _returnFechaRegistro.setSegundos(-1053328279);
            _return.setFechaRegistro(_returnFechaRegistro);
            webservices.TEstadoWS _returnEstado = webservices.TEstadoWS.INGRESADA;
            _return.setEstado(_returnEstado);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#obtenerSocios(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerSocios() { 
        LOG.info("Executing operation obtenerSocios");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1236929560";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#buscarActDep(java.lang.String  arg0 )*
     */
    public webservices.DtActividadWS buscarActDep(java.lang.String arg0) throws ActividadDeportivaException_Exception    { 
        LOG.info("Executing operation buscarActDep");
        System.out.println(arg0);
        try {
            webservices.DtActividadWS _return = new webservices.DtActividadWS();
            java.util.List<java.lang.String> _returnClases = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnClasesVal1 = "_returnClasesVal1341564009";
            _returnClases.add(_returnClasesVal1);
            _return.getClases().addAll(_returnClases);
            java.util.List<java.lang.String> _returnCup = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCupVal1 = "_returnCupVal147625998";
            _returnCup.add(_returnCupVal1);
            _return.getCup().addAll(_returnCup);
            java.util.List<java.lang.String> _returnCategorias = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCategoriasVal1 = "_returnCategoriasVal1041107088";
            _returnCategorias.add(_returnCategoriasVal1);
            _return.getCategorias().addAll(_returnCategorias);
            _return.setNombre("Nombre-1707647511");
            _return.setDescripcion("Descripcion-169603632");
            _return.setCreador("Creador825275945");
            _return.setImgName("ImgName1171629718");
            _return.setDuracionMinutos(-1394231697);
            _return.setCosto(0.66250074f);
            webservices.DtFechaWS _returnFechaRegistro = new webservices.DtFechaWS();
            _returnFechaRegistro.setAnio(-1441533146);
            _returnFechaRegistro.setMes(1847154045);
            _returnFechaRegistro.setDia(-552177958);
            _returnFechaRegistro.setHoras(-1497636642);
            _returnFechaRegistro.setMinutos(-1630989781);
            _returnFechaRegistro.setSegundos(-46753181);
            _return.setFechaRegistro(_returnFechaRegistro);
            webservices.TEstadoWS _returnEstado = webservices.TEstadoWS.INGRESADA;
            _return.setEstado(_returnEstado);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#obtenerInstituciones(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerInstituciones() { 
        LOG.info("Executing operation obtenerInstituciones");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1794185353";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#finalizarActividad(java.lang.String  arg0 )*
     */
    public void finalizarActividad(java.lang.String arg0) { 
        LOG.info("Executing operation finalizarActividad");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSActividadController#ingresarDatosActividadDep(java.lang.String  arg0 ,)webservices.DtActividadWS  arg1 )*
     */
    public boolean ingresarDatosActividadDep(java.lang.String arg0,DtActividadWS arg1) throws ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation ingresarDatosActividadDep");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

}
