
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-06T19:16:01.858-03:00
 * Generated source version: 2.7.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSClaseControllerService",
                      portName = "WSClaseControllerPort",
                      targetNamespace = "http://webServices/",
                      wsdlLocation = "http://localhost:9129/entrenamosuy/claseController?wsdl",
                      endpointInterface = "webservices.WSClaseController")
                      
public class WSClaseControllerImpl implements WSClaseController {

    private static final Logger LOG = Logger.getLogger(WSClaseControllerImpl.class.getName());

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerInstitucionActDep(java.lang.String  arg0 )*
     */
    public java.lang.String obtenerInstitucionActDep(java.lang.String arg0) { 
        LOG.info("Executing operation obtenerInstitucionActDep");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1276786896";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#seleccionarClase(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public webservices.DtClaseWS seleccionarClase(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) throws ClaseException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation seleccionarClase");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            webservices.DtClaseWS _return = new webservices.DtClaseWS();
            java.util.List<java.lang.String> _returnAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAlumnosVal1 = "_returnAlumnosVal-478134649";
            _returnAlumnos.add(_returnAlumnosVal1);
            _return.getAlumnos().addAll(_returnAlumnos);
            java.util.List<java.lang.Integer> _returnCalificacionesData = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnCalificacionesDataVal1 = Integer.valueOf(1242212980);
            _returnCalificacionesData.add(_returnCalificacionesDataVal1);
            _return.getCalificacionesData().addAll(_returnCalificacionesData);
            java.util.List<java.lang.String> _returnCalificacionesHead = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCalificacionesHeadVal1 = "_returnCalificacionesHeadVal1576505719";
            _returnCalificacionesHead.add(_returnCalificacionesHeadVal1);
            _return.getCalificacionesHead().addAll(_returnCalificacionesHead);
            _return.setCorreoProfesor("CorreoProfesor-770471005");
            webservices.DtFechaWS _returnFechaClase = new webservices.DtFechaWS();
            _returnFechaClase.setAnio(1430504515);
            _returnFechaClase.setMes(1517626864);
            _returnFechaClase.setDia(1721356739);
            _returnFechaClase.setHoras(243996361);
            _returnFechaClase.setMinutos(524615741);
            _returnFechaClase.setSegundos(-400791697);
            _return.setFechaClase(_returnFechaClase);
            webservices.DtFechaWS _returnFechaRegistro = new webservices.DtFechaWS();
            _returnFechaRegistro.setAnio(1537298341);
            _returnFechaRegistro.setMes(242296784);
            _returnFechaRegistro.setDia(410856947);
            _returnFechaRegistro.setHoras(23549953);
            _returnFechaRegistro.setMinutos(385082818);
            _returnFechaRegistro.setSegundos(-349076119);
            _return.setFechaRegistro(_returnFechaRegistro);
            _return.setImgName("ImgName393411469");
            _return.setMaxSocios(1939135452);
            _return.setMinSocios(370018372);
            _return.setNicknameProfesor("NicknameProfesor1792366649");
            _return.setNombre("Nombre323560476");
            webservices.DtPremioWS _returnPremio = new webservices.DtPremioWS();
            _returnPremio.setDescripcion("Descripcion725391691");
            _returnPremio.setCantidad(1149678266);
            webservices.DtFechaWS _returnPremioFechaSorteo = new webservices.DtFechaWS();
            _returnPremioFechaSorteo.setAnio(-937800463);
            _returnPremioFechaSorteo.setMes(-525997530);
            _returnPremioFechaSorteo.setDia(77642469);
            _returnPremioFechaSorteo.setHoras(1128910908);
            _returnPremioFechaSorteo.setMinutos(-1190050917);
            _returnPremioFechaSorteo.setSegundos(238630498);
            _returnPremio.setFechaSorteo(_returnPremioFechaSorteo);
            java.util.List<java.lang.String> _returnPremioGanadores = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnPremioGanadoresVal1 = "_returnPremioGanadoresVal-2061688574";
            _returnPremioGanadores.add(_returnPremioGanadoresVal1);
            _returnPremio.getGanadores().addAll(_returnPremioGanadores);
            _return.setPremio(_returnPremio);
            java.util.List<java.lang.String> _returnSoloNickAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnSoloNickAlumnosVal1 = "_returnSoloNickAlumnosVal1917747666";
            _returnSoloNickAlumnos.add(_returnSoloNickAlumnosVal1);
            _return.getSoloNickAlumnos().addAll(_returnSoloNickAlumnos);
            _return.setUrlVideo("UrlVideo-249028553");
            _return.setUrlwebsite("Urlwebsite-1262526785");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClaseException_Exception("ClaseException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerActividades(java.lang.String  arg0 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerActividades(java.lang.String arg0) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerActividades");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-623659413";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#getCuponerasSocioClase(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public net.java.dev.jaxb.array.StringArray getCuponerasSocioClase(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation getCuponerasSocioClase");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-822024427";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerClases(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerClases(java.lang.String arg0,java.lang.String arg1) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerClases");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal229085318";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerActividadesAprobadas(java.lang.String  arg0 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerActividadesAprobadas(java.lang.String arg0) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerActividadesAprobadas");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1606080939";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerUsuarios(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerUsuarios() { 
        LOG.info("Executing operation obtenerUsuarios");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal92068944";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#buscarClase(java.lang.String  arg0 )*
     */
    public webservices.DtClaseWS buscarClase(java.lang.String arg0) throws ClaseException_Exception    { 
        LOG.info("Executing operation buscarClase");
        System.out.println(arg0);
        try {
            webservices.DtClaseWS _return = new webservices.DtClaseWS();
            java.util.List<java.lang.String> _returnAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAlumnosVal1 = "_returnAlumnosVal-1293071081";
            _returnAlumnos.add(_returnAlumnosVal1);
            _return.getAlumnos().addAll(_returnAlumnos);
            java.util.List<java.lang.Integer> _returnCalificacionesData = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnCalificacionesDataVal1 = Integer.valueOf(-2098799836);
            _returnCalificacionesData.add(_returnCalificacionesDataVal1);
            _return.getCalificacionesData().addAll(_returnCalificacionesData);
            java.util.List<java.lang.String> _returnCalificacionesHead = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCalificacionesHeadVal1 = "_returnCalificacionesHeadVal-687906415";
            _returnCalificacionesHead.add(_returnCalificacionesHeadVal1);
            _return.getCalificacionesHead().addAll(_returnCalificacionesHead);
            _return.setCorreoProfesor("CorreoProfesor-566353538");
            webservices.DtFechaWS _returnFechaClase = new webservices.DtFechaWS();
            _returnFechaClase.setAnio(246736767);
            _returnFechaClase.setMes(2047151068);
            _returnFechaClase.setDia(-1714598750);
            _returnFechaClase.setHoras(-203900720);
            _returnFechaClase.setMinutos(-1288538120);
            _returnFechaClase.setSegundos(-333967049);
            _return.setFechaClase(_returnFechaClase);
            webservices.DtFechaWS _returnFechaRegistro = new webservices.DtFechaWS();
            _returnFechaRegistro.setAnio(1659116759);
            _returnFechaRegistro.setMes(-1348181274);
            _returnFechaRegistro.setDia(137856972);
            _returnFechaRegistro.setHoras(-843604138);
            _returnFechaRegistro.setMinutos(1843366967);
            _returnFechaRegistro.setSegundos(-1109213419);
            _return.setFechaRegistro(_returnFechaRegistro);
            _return.setImgName("ImgName-1951328309");
            _return.setMaxSocios(97709057);
            _return.setMinSocios(1369610581);
            _return.setNicknameProfesor("NicknameProfesor1010972573");
            _return.setNombre("Nombre395111025");
            webservices.DtPremioWS _returnPremio = new webservices.DtPremioWS();
            _returnPremio.setDescripcion("Descripcion-1038247937");
            _returnPremio.setCantidad(-1110943716);
            webservices.DtFechaWS _returnPremioFechaSorteo = new webservices.DtFechaWS();
            _returnPremioFechaSorteo.setAnio(723975457);
            _returnPremioFechaSorteo.setMes(380030023);
            _returnPremioFechaSorteo.setDia(-1554949721);
            _returnPremioFechaSorteo.setHoras(-364213554);
            _returnPremioFechaSorteo.setMinutos(751027539);
            _returnPremioFechaSorteo.setSegundos(60259977);
            _returnPremio.setFechaSorteo(_returnPremioFechaSorteo);
            java.util.List<java.lang.String> _returnPremioGanadores = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnPremioGanadoresVal1 = "_returnPremioGanadoresVal692534455";
            _returnPremioGanadores.add(_returnPremioGanadoresVal1);
            _returnPremio.getGanadores().addAll(_returnPremioGanadores);
            _return.setPremio(_returnPremio);
            java.util.List<java.lang.String> _returnSoloNickAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnSoloNickAlumnosVal1 = "_returnSoloNickAlumnosVal-49658038";
            _returnSoloNickAlumnos.add(_returnSoloNickAlumnosVal1);
            _return.getSoloNickAlumnos().addAll(_returnSoloNickAlumnos);
            _return.setUrlVideo("UrlVideo-680312594");
            _return.setUrlwebsite("Urlwebsite766846984");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClaseException_Exception("ClaseException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerSocios(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerSocios() { 
        LOG.info("Executing operation obtenerSocios");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1010529437";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerProfesores(java.lang.String  arg0 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerProfesores(java.lang.String arg0) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerProfesores");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-2132333427";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerInstituciones(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerInstituciones() { 
        LOG.info("Executing operation obtenerInstituciones");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal308182249";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#getCuponerasDisponibles(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public net.java.dev.jaxb.array.StringArray getCuponerasDisponibles(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) throws UsuarioNoExisteException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation getCuponerasDisponibles");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1529835602";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#ingresarDatosClase(java.lang.String  arg0 ,)java.lang.String  arg1 ,)webservices.DtClaseWS  arg2 )*
     */
    public int ingresarDatosClase(java.lang.String arg0,java.lang.String arg1,DtClaseWS arg2) throws UsuarioNoExisteException_Exception , FechaInvalidaException_Exception , ClaseException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation ingresarDatosClase");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            int _return = 1443148977;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
        //throw new FechaInvalidaException_Exception("FechaInvalidaException...");
        //throw new ClaseException_Exception("ClaseException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#inscribirSocio(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)webservices.TRegWS  arg4 ,)webservices.DtFechaWS  arg5 ,)java.lang.String  arg6 )*
     */
    public void inscribirSocio(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,TRegWS arg4,DtFechaWS arg5,java.lang.String arg6) throws ClaseException_Exception , FechaInvalidaException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception , NoExisteCuponeraException_Exception , UsuarioNoExisteException_Exception    { 
        LOG.info("Executing operation inscribirSocio");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClaseException_Exception("ClaseException...");
        //throw new FechaInvalidaException_Exception("FechaInvalidaException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
        //throw new NoExisteCuponeraException_Exception("NoExisteCuponeraException...");
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#sortearPremios(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public net.java.dev.jaxb.array.StringArray sortearPremios(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) throws ClaseException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation sortearPremios");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal2044062842";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClaseException_Exception("ClaseException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

}
