
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package webservices;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-07T14:14:54.842-03:00
 * Generated source version: 2.7.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSClaseControllerService",
                      portName = "WSClaseControllerPort",
                      targetNamespace = "http://webServices/",
                      endpointInterface = "webservices.WSClaseController")
                      
public class WSClaseControllerImpl implements WSClaseController {

    private static final Logger LOG = Logger.getLogger(WSClaseControllerImpl.class.getName());

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerInstitucionActDep(java.lang.String  arg0 )*
     */
    public java.lang.String obtenerInstitucionActDep(java.lang.String arg0) { 
        LOG.info("Executing operation obtenerInstitucionActDep");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-880007547";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#seleccionarClase(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public webservices.DtClaseWS seleccionarClase(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) throws ClaseException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation seleccionarClase");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            webservices.DtClaseWS _return = new webservices.DtClaseWS();
            java.util.List<java.lang.String> _returnAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAlumnosVal1 = "_returnAlumnosVal2070207550";
            _returnAlumnos.add(_returnAlumnosVal1);
            _return.getAlumnos().addAll(_returnAlumnos);
            java.util.List<java.lang.Integer> _returnCalificacionesData = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnCalificacionesDataVal1 = Integer.valueOf(-1564347574);
            _returnCalificacionesData.add(_returnCalificacionesDataVal1);
            _return.getCalificacionesData().addAll(_returnCalificacionesData);
            java.util.List<java.lang.String> _returnCalificacionesHead = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCalificacionesHeadVal1 = "_returnCalificacionesHeadVal-1731762085";
            _returnCalificacionesHead.add(_returnCalificacionesHeadVal1);
            _return.getCalificacionesHead().addAll(_returnCalificacionesHead);
            _return.setCorreoProfesor("CorreoProfesor-741999098");
            webservices.DtFechaWS _returnFechaClase = new webservices.DtFechaWS();
            _returnFechaClase.setAnio(-1969289981);
            _returnFechaClase.setMes(2102018938);
            _returnFechaClase.setDia(1270900651);
            _returnFechaClase.setHoras(-1596606890);
            _returnFechaClase.setMinutos(-1818655419);
            _returnFechaClase.setSegundos(1367007204);
            _return.setFechaClase(_returnFechaClase);
            webservices.DtFechaWS _returnFechaRegistro = new webservices.DtFechaWS();
            _returnFechaRegistro.setAnio(1282390525);
            _returnFechaRegistro.setMes(395487623);
            _returnFechaRegistro.setDia(-1140359616);
            _returnFechaRegistro.setHoras(-1381768112);
            _returnFechaRegistro.setMinutos(1216080051);
            _returnFechaRegistro.setSegundos(468818216);
            _return.setFechaRegistro(_returnFechaRegistro);
            _return.setImgName("ImgName2031266054");
            _return.setMaxSocios(-920140952);
            _return.setMinSocios(1404440001);
            _return.setNicknameProfesor("NicknameProfesor780771544");
            _return.setNombre("Nombre190289794");
            webservices.DtPremioWS _returnPremio = new webservices.DtPremioWS();
            _returnPremio.setDescripcion("Descripcion1492946278");
            _returnPremio.setCantidad(-828725687);
            webservices.DtFechaWS _returnPremioFechaSorteo = new webservices.DtFechaWS();
            _returnPremioFechaSorteo.setAnio(-1243791845);
            _returnPremioFechaSorteo.setMes(1601601977);
            _returnPremioFechaSorteo.setDia(2020503054);
            _returnPremioFechaSorteo.setHoras(-214275196);
            _returnPremioFechaSorteo.setMinutos(-628391568);
            _returnPremioFechaSorteo.setSegundos(-1752358061);
            _returnPremio.setFechaSorteo(_returnPremioFechaSorteo);
            java.util.List<java.lang.String> _returnPremioGanadores = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnPremioGanadoresVal1 = "_returnPremioGanadoresVal1555535327";
            _returnPremioGanadores.add(_returnPremioGanadoresVal1);
            _returnPremio.getGanadores().addAll(_returnPremioGanadores);
            _return.setPremio(_returnPremio);
            java.util.List<java.lang.String> _returnSoloNickAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnSoloNickAlumnosVal1 = "_returnSoloNickAlumnosVal-597862935";
            _returnSoloNickAlumnos.add(_returnSoloNickAlumnosVal1);
            _return.getSoloNickAlumnos().addAll(_returnSoloNickAlumnos);
            _return.setUrlVideo("UrlVideo591051938");
            _return.setUrlwebsite("Urlwebsite-734892710");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClaseException_Exception("ClaseException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerActividades(java.lang.String  arg0 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerActividades(java.lang.String arg0) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerActividades");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-493813115";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#getCuponerasSocioClase(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public net.java.dev.jaxb.array.StringArray getCuponerasSocioClase(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation getCuponerasSocioClase");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1127231111";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerClases(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerClases(java.lang.String arg0,java.lang.String arg1) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerClases");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-397458850";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerActividadesAprobadas(java.lang.String  arg0 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerActividadesAprobadas(java.lang.String arg0) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerActividadesAprobadas");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1646981056";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerUsuarios(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerUsuarios() { 
        LOG.info("Executing operation obtenerUsuarios");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal253942417";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#buscarClase(java.lang.String  arg0 )*
     */
    public webservices.DtClaseWS buscarClase(java.lang.String arg0) throws ClaseException_Exception    { 
        LOG.info("Executing operation buscarClase");
        System.out.println(arg0);
        try {
            webservices.DtClaseWS _return = new webservices.DtClaseWS();
            java.util.List<java.lang.String> _returnAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAlumnosVal1 = "_returnAlumnosVal-101756234";
            _returnAlumnos.add(_returnAlumnosVal1);
            _return.getAlumnos().addAll(_returnAlumnos);
            java.util.List<java.lang.Integer> _returnCalificacionesData = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnCalificacionesDataVal1 = Integer.valueOf(-1919546619);
            _returnCalificacionesData.add(_returnCalificacionesDataVal1);
            _return.getCalificacionesData().addAll(_returnCalificacionesData);
            java.util.List<java.lang.String> _returnCalificacionesHead = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCalificacionesHeadVal1 = "_returnCalificacionesHeadVal-1914035674";
            _returnCalificacionesHead.add(_returnCalificacionesHeadVal1);
            _return.getCalificacionesHead().addAll(_returnCalificacionesHead);
            _return.setCorreoProfesor("CorreoProfesor1089622123");
            webservices.DtFechaWS _returnFechaClase = new webservices.DtFechaWS();
            _returnFechaClase.setAnio(1275563502);
            _returnFechaClase.setMes(-1976282429);
            _returnFechaClase.setDia(174679387);
            _returnFechaClase.setHoras(618020998);
            _returnFechaClase.setMinutos(5254646);
            _returnFechaClase.setSegundos(1386906848);
            _return.setFechaClase(_returnFechaClase);
            webservices.DtFechaWS _returnFechaRegistro = new webservices.DtFechaWS();
            _returnFechaRegistro.setAnio(1374221090);
            _returnFechaRegistro.setMes(500891350);
            _returnFechaRegistro.setDia(1049605440);
            _returnFechaRegistro.setHoras(1992951894);
            _returnFechaRegistro.setMinutos(58871480);
            _returnFechaRegistro.setSegundos(-258930817);
            _return.setFechaRegistro(_returnFechaRegistro);
            _return.setImgName("ImgName816762771");
            _return.setMaxSocios(-882720350);
            _return.setMinSocios(1204233364);
            _return.setNicknameProfesor("NicknameProfesor1640597198");
            _return.setNombre("Nombre-401380118");
            webservices.DtPremioWS _returnPremio = new webservices.DtPremioWS();
            _returnPremio.setDescripcion("Descripcion1852202462");
            _returnPremio.setCantidad(-676578832);
            webservices.DtFechaWS _returnPremioFechaSorteo = new webservices.DtFechaWS();
            _returnPremioFechaSorteo.setAnio(-2122388372);
            _returnPremioFechaSorteo.setMes(47720092);
            _returnPremioFechaSorteo.setDia(1502395151);
            _returnPremioFechaSorteo.setHoras(666194056);
            _returnPremioFechaSorteo.setMinutos(1809251792);
            _returnPremioFechaSorteo.setSegundos(1362252476);
            _returnPremio.setFechaSorteo(_returnPremioFechaSorteo);
            java.util.List<java.lang.String> _returnPremioGanadores = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnPremioGanadoresVal1 = "_returnPremioGanadoresVal476447164";
            _returnPremioGanadores.add(_returnPremioGanadoresVal1);
            _returnPremio.getGanadores().addAll(_returnPremioGanadores);
            _return.setPremio(_returnPremio);
            java.util.List<java.lang.String> _returnSoloNickAlumnos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnSoloNickAlumnosVal1 = "_returnSoloNickAlumnosVal-787152223";
            _returnSoloNickAlumnos.add(_returnSoloNickAlumnosVal1);
            _return.getSoloNickAlumnos().addAll(_returnSoloNickAlumnos);
            _return.setUrlVideo("UrlVideo-150004747");
            _return.setUrlwebsite("Urlwebsite-2086966846");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClaseException_Exception("ClaseException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerSocios(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerSocios() { 
        LOG.info("Executing operation obtenerSocios");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal545014719";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerProfesores(java.lang.String  arg0 )*
     */
    public net.java.dev.jaxb.array.StringArray obtenerProfesores(java.lang.String arg0) throws InstitucionException_Exception    { 
        LOG.info("Executing operation obtenerProfesores");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal203414348";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#obtenerInstituciones(*
     */
    public net.java.dev.jaxb.array.StringArray obtenerInstituciones() { 
        LOG.info("Executing operation obtenerInstituciones");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1795510195";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#getCuponerasDisponibles(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public net.java.dev.jaxb.array.StringArray getCuponerasDisponibles(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) throws UsuarioNoExisteException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation getCuponerasDisponibles");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-864509334";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#ingresarDatosClase(java.lang.String  arg0 ,)java.lang.String  arg1 ,)webservices.DtClaseWS  arg2 )*
     */
    public int ingresarDatosClase(java.lang.String arg0,java.lang.String arg1,DtClaseWS arg2) throws UsuarioNoExisteException_Exception , FechaInvalidaException_Exception , ClaseException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation ingresarDatosClase");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            int _return = -2114997154;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
        //throw new FechaInvalidaException_Exception("FechaInvalidaException...");
        //throw new ClaseException_Exception("ClaseException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#inscribirSocio(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)webservices.TRegWS  arg4 ,)webservices.DtFechaWS  arg5 ,)java.lang.String  arg6 )*
     */
    public void inscribirSocio(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,TRegWS arg4,DtFechaWS arg5,java.lang.String arg6) throws ClaseException_Exception , FechaInvalidaException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception , NoExisteCuponeraException_Exception , UsuarioNoExisteException_Exception    { 
        LOG.info("Executing operation inscribirSocio");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClaseException_Exception("ClaseException...");
        //throw new FechaInvalidaException_Exception("FechaInvalidaException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
        //throw new NoExisteCuponeraException_Exception("NoExisteCuponeraException...");
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSClaseController#sortearPremios(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public net.java.dev.jaxb.array.StringArray sortearPremios(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) throws ClaseException_Exception , ActividadDeportivaException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation sortearPremios");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1336028907";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ClaseException_Exception("ClaseException...");
        //throw new ActividadDeportivaException_Exception("ActividadDeportivaException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

}
