
package webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-06T19:16:01.785-03:00
 * Generated source version: 2.7.9
 * 
 */
public final class WSClaseController_WSClaseControllerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webServices/", "WSClaseControllerService");

    private WSClaseController_WSClaseControllerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSClaseControllerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSClaseControllerService ss = new WSClaseControllerService(wsdlURL, SERVICE_NAME);
        WSClaseController port = ss.getWSClaseControllerPort();  
        
        {
        System.out.println("Invoking obtenerInstitucionActDep...");
        java.lang.String _obtenerInstitucionActDep_arg0 = "_obtenerInstitucionActDep_arg01112434999";
        java.lang.String _obtenerInstitucionActDep__return = port.obtenerInstitucionActDep(_obtenerInstitucionActDep_arg0);
        System.out.println("obtenerInstitucionActDep.result=" + _obtenerInstitucionActDep__return);


        }
        {
        System.out.println("Invoking seleccionarClase...");
        java.lang.String _seleccionarClase_arg0 = "_seleccionarClase_arg0-1548307262";
        java.lang.String _seleccionarClase_arg1 = "_seleccionarClase_arg1-1775622147";
        java.lang.String _seleccionarClase_arg2 = "_seleccionarClase_arg2900794494";
        try {
            webservices.DtClaseWS _seleccionarClase__return = port.seleccionarClase(_seleccionarClase_arg0, _seleccionarClase_arg1, _seleccionarClase_arg2);
            System.out.println("seleccionarClase.result=" + _seleccionarClase__return);

        } catch (ClaseException_Exception e) { 
            System.out.println("Expected exception: ClaseException has occurred.");
            System.out.println(e.toString());
        } catch (ActividadDeportivaException_Exception e) { 
            System.out.println("Expected exception: ActividadDeportivaException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerActividades...");
        java.lang.String _obtenerActividades_arg0 = "_obtenerActividades_arg047452796";
        try {
            net.java.dev.jaxb.array.StringArray _obtenerActividades__return = port.obtenerActividades(_obtenerActividades_arg0);
            System.out.println("obtenerActividades.result=" + _obtenerActividades__return);

        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCuponerasSocioClase...");
        java.lang.String _getCuponerasSocioClase_arg0 = "_getCuponerasSocioClase_arg0-366581059";
        java.lang.String _getCuponerasSocioClase_arg1 = "_getCuponerasSocioClase_arg1-74631268";
        java.lang.String _getCuponerasSocioClase_arg2 = "_getCuponerasSocioClase_arg21014318633";
        java.lang.String _getCuponerasSocioClase_arg3 = "_getCuponerasSocioClase_arg3-1349598979";
        net.java.dev.jaxb.array.StringArray _getCuponerasSocioClase__return = port.getCuponerasSocioClase(_getCuponerasSocioClase_arg0, _getCuponerasSocioClase_arg1, _getCuponerasSocioClase_arg2, _getCuponerasSocioClase_arg3);
        System.out.println("getCuponerasSocioClase.result=" + _getCuponerasSocioClase__return);


        }
        {
        System.out.println("Invoking obtenerClases...");
        java.lang.String _obtenerClases_arg0 = "_obtenerClases_arg0879503694";
        java.lang.String _obtenerClases_arg1 = "_obtenerClases_arg11019306969";
        try {
            net.java.dev.jaxb.array.StringArray _obtenerClases__return = port.obtenerClases(_obtenerClases_arg0, _obtenerClases_arg1);
            System.out.println("obtenerClases.result=" + _obtenerClases__return);

        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerActividadesAprobadas...");
        java.lang.String _obtenerActividadesAprobadas_arg0 = "_obtenerActividadesAprobadas_arg0574793243";
        try {
            net.java.dev.jaxb.array.StringArray _obtenerActividadesAprobadas__return = port.obtenerActividadesAprobadas(_obtenerActividadesAprobadas_arg0);
            System.out.println("obtenerActividadesAprobadas.result=" + _obtenerActividadesAprobadas__return);

        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerUsuarios...");
        net.java.dev.jaxb.array.StringArray _obtenerUsuarios__return = port.obtenerUsuarios();
        System.out.println("obtenerUsuarios.result=" + _obtenerUsuarios__return);


        }
        {
        System.out.println("Invoking buscarClase...");
        java.lang.String _buscarClase_arg0 = "_buscarClase_arg01912579954";
        try {
            webservices.DtClaseWS _buscarClase__return = port.buscarClase(_buscarClase_arg0);
            System.out.println("buscarClase.result=" + _buscarClase__return);

        } catch (ClaseException_Exception e) { 
            System.out.println("Expected exception: ClaseException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerSocios...");
        net.java.dev.jaxb.array.StringArray _obtenerSocios__return = port.obtenerSocios();
        System.out.println("obtenerSocios.result=" + _obtenerSocios__return);


        }
        {
        System.out.println("Invoking obtenerProfesores...");
        java.lang.String _obtenerProfesores_arg0 = "_obtenerProfesores_arg0-590073148";
        try {
            net.java.dev.jaxb.array.StringArray _obtenerProfesores__return = port.obtenerProfesores(_obtenerProfesores_arg0);
            System.out.println("obtenerProfesores.result=" + _obtenerProfesores__return);

        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerInstituciones...");
        net.java.dev.jaxb.array.StringArray _obtenerInstituciones__return = port.obtenerInstituciones();
        System.out.println("obtenerInstituciones.result=" + _obtenerInstituciones__return);


        }
        {
        System.out.println("Invoking getCuponerasDisponibles...");
        java.lang.String _getCuponerasDisponibles_arg0 = "_getCuponerasDisponibles_arg01157700278";
        java.lang.String _getCuponerasDisponibles_arg1 = "_getCuponerasDisponibles_arg11155197040";
        java.lang.String _getCuponerasDisponibles_arg2 = "_getCuponerasDisponibles_arg2-1203269899";
        try {
            net.java.dev.jaxb.array.StringArray _getCuponerasDisponibles__return = port.getCuponerasDisponibles(_getCuponerasDisponibles_arg0, _getCuponerasDisponibles_arg1, _getCuponerasDisponibles_arg2);
            System.out.println("getCuponerasDisponibles.result=" + _getCuponerasDisponibles__return);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        } catch (ActividadDeportivaException_Exception e) { 
            System.out.println("Expected exception: ActividadDeportivaException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking ingresarDatosClase...");
        java.lang.String _ingresarDatosClase_arg0 = "_ingresarDatosClase_arg0-1431903332";
        java.lang.String _ingresarDatosClase_arg1 = "_ingresarDatosClase_arg11131635672";
        webservices.DtClaseWS _ingresarDatosClase_arg2 = new webservices.DtClaseWS();
        java.util.List<java.lang.String> _ingresarDatosClase_arg2Alumnos = new java.util.ArrayList<java.lang.String>();
        java.lang.String _ingresarDatosClase_arg2AlumnosVal1 = "_ingresarDatosClase_arg2AlumnosVal-1725668573";
        _ingresarDatosClase_arg2Alumnos.add(_ingresarDatosClase_arg2AlumnosVal1);
        _ingresarDatosClase_arg2.getAlumnos().addAll(_ingresarDatosClase_arg2Alumnos);
        java.util.List<java.lang.Integer> _ingresarDatosClase_arg2CalificacionesData = new java.util.ArrayList<java.lang.Integer>();
        java.lang.Integer _ingresarDatosClase_arg2CalificacionesDataVal1 = Integer.valueOf(-353734392);
        _ingresarDatosClase_arg2CalificacionesData.add(_ingresarDatosClase_arg2CalificacionesDataVal1);
        _ingresarDatosClase_arg2.getCalificacionesData().addAll(_ingresarDatosClase_arg2CalificacionesData);
        java.util.List<java.lang.String> _ingresarDatosClase_arg2CalificacionesHead = new java.util.ArrayList<java.lang.String>();
        java.lang.String _ingresarDatosClase_arg2CalificacionesHeadVal1 = "_ingresarDatosClase_arg2CalificacionesHeadVal1719721528";
        _ingresarDatosClase_arg2CalificacionesHead.add(_ingresarDatosClase_arg2CalificacionesHeadVal1);
        _ingresarDatosClase_arg2.getCalificacionesHead().addAll(_ingresarDatosClase_arg2CalificacionesHead);
        _ingresarDatosClase_arg2.setCorreoProfesor("CorreoProfesor1844065313");
        webservices.DtFechaWS _ingresarDatosClase_arg2FechaClase = new webservices.DtFechaWS();
        _ingresarDatosClase_arg2FechaClase.setAnio(-393677081);
        _ingresarDatosClase_arg2FechaClase.setMes(1772367324);
        _ingresarDatosClase_arg2FechaClase.setDia(-1688879665);
        _ingresarDatosClase_arg2FechaClase.setHoras(750770078);
        _ingresarDatosClase_arg2FechaClase.setMinutos(-1047593674);
        _ingresarDatosClase_arg2FechaClase.setSegundos(886825680);
        _ingresarDatosClase_arg2.setFechaClase(_ingresarDatosClase_arg2FechaClase);
        webservices.DtFechaWS _ingresarDatosClase_arg2FechaRegistro = new webservices.DtFechaWS();
        _ingresarDatosClase_arg2FechaRegistro.setAnio(-1779006299);
        _ingresarDatosClase_arg2FechaRegistro.setMes(1577489828);
        _ingresarDatosClase_arg2FechaRegistro.setDia(1774879657);
        _ingresarDatosClase_arg2FechaRegistro.setHoras(907519287);
        _ingresarDatosClase_arg2FechaRegistro.setMinutos(1557412219);
        _ingresarDatosClase_arg2FechaRegistro.setSegundos(1808528181);
        _ingresarDatosClase_arg2.setFechaRegistro(_ingresarDatosClase_arg2FechaRegistro);
        _ingresarDatosClase_arg2.setImgName("ImgName-1302959990");
        _ingresarDatosClase_arg2.setMaxSocios(933930334);
        _ingresarDatosClase_arg2.setMinSocios(1481271367);
        _ingresarDatosClase_arg2.setNicknameProfesor("NicknameProfesor-1587333209");
        _ingresarDatosClase_arg2.setNombre("Nombre-1159058265");
        webservices.DtPremioWS _ingresarDatosClase_arg2Premio = new webservices.DtPremioWS();
        _ingresarDatosClase_arg2Premio.setDescripcion("Descripcion-688652852");
        _ingresarDatosClase_arg2Premio.setCantidad(-263947736);
        webservices.DtFechaWS _ingresarDatosClase_arg2PremioFechaSorteo = new webservices.DtFechaWS();
        _ingresarDatosClase_arg2PremioFechaSorteo.setAnio(-2067720313);
        _ingresarDatosClase_arg2PremioFechaSorteo.setMes(-1684369816);
        _ingresarDatosClase_arg2PremioFechaSorteo.setDia(623162059);
        _ingresarDatosClase_arg2PremioFechaSorteo.setHoras(-372500333);
        _ingresarDatosClase_arg2PremioFechaSorteo.setMinutos(623684026);
        _ingresarDatosClase_arg2PremioFechaSorteo.setSegundos(396378660);
        _ingresarDatosClase_arg2Premio.setFechaSorteo(_ingresarDatosClase_arg2PremioFechaSorteo);
        java.util.List<java.lang.String> _ingresarDatosClase_arg2PremioGanadores = new java.util.ArrayList<java.lang.String>();
        java.lang.String _ingresarDatosClase_arg2PremioGanadoresVal1 = "_ingresarDatosClase_arg2PremioGanadoresVal350725671";
        _ingresarDatosClase_arg2PremioGanadores.add(_ingresarDatosClase_arg2PremioGanadoresVal1);
        _ingresarDatosClase_arg2Premio.getGanadores().addAll(_ingresarDatosClase_arg2PremioGanadores);
        _ingresarDatosClase_arg2.setPremio(_ingresarDatosClase_arg2Premio);
        java.util.List<java.lang.String> _ingresarDatosClase_arg2SoloNickAlumnos = new java.util.ArrayList<java.lang.String>();
        java.lang.String _ingresarDatosClase_arg2SoloNickAlumnosVal1 = "_ingresarDatosClase_arg2SoloNickAlumnosVal-1388441646";
        _ingresarDatosClase_arg2SoloNickAlumnos.add(_ingresarDatosClase_arg2SoloNickAlumnosVal1);
        _ingresarDatosClase_arg2.getSoloNickAlumnos().addAll(_ingresarDatosClase_arg2SoloNickAlumnos);
        _ingresarDatosClase_arg2.setUrlVideo("UrlVideo-567801115");
        _ingresarDatosClase_arg2.setUrlwebsite("Urlwebsite-178168913");
        try {
            int _ingresarDatosClase__return = port.ingresarDatosClase(_ingresarDatosClase_arg0, _ingresarDatosClase_arg1, _ingresarDatosClase_arg2);
            System.out.println("ingresarDatosClase.result=" + _ingresarDatosClase__return);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        } catch (FechaInvalidaException_Exception e) { 
            System.out.println("Expected exception: FechaInvalidaException has occurred.");
            System.out.println(e.toString());
        } catch (ClaseException_Exception e) { 
            System.out.println("Expected exception: ClaseException has occurred.");
            System.out.println(e.toString());
        } catch (ActividadDeportivaException_Exception e) { 
            System.out.println("Expected exception: ActividadDeportivaException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking inscribirSocio...");
        java.lang.String _inscribirSocio_arg0 = "_inscribirSocio_arg0397312821";
        java.lang.String _inscribirSocio_arg1 = "_inscribirSocio_arg11741055151";
        java.lang.String _inscribirSocio_arg2 = "_inscribirSocio_arg2783635214";
        java.lang.String _inscribirSocio_arg3 = "_inscribirSocio_arg31185889591";
        webservices.TRegWS _inscribirSocio_arg4 = webservices.TRegWS.GENERAL;
        webservices.DtFechaWS _inscribirSocio_arg5 = new webservices.DtFechaWS();
        _inscribirSocio_arg5.setAnio(-1214541460);
        _inscribirSocio_arg5.setMes(272810371);
        _inscribirSocio_arg5.setDia(-923525296);
        _inscribirSocio_arg5.setHoras(1340819773);
        _inscribirSocio_arg5.setMinutos(-42197515);
        _inscribirSocio_arg5.setSegundos(-405585158);
        java.lang.String _inscribirSocio_arg6 = "_inscribirSocio_arg6-584546740";
        try {
            port.inscribirSocio(_inscribirSocio_arg0, _inscribirSocio_arg1, _inscribirSocio_arg2, _inscribirSocio_arg3, _inscribirSocio_arg4, _inscribirSocio_arg5, _inscribirSocio_arg6);

        } catch (ClaseException_Exception e) { 
            System.out.println("Expected exception: ClaseException has occurred.");
            System.out.println(e.toString());
        } catch (FechaInvalidaException_Exception e) { 
            System.out.println("Expected exception: FechaInvalidaException has occurred.");
            System.out.println(e.toString());
        } catch (ActividadDeportivaException_Exception e) { 
            System.out.println("Expected exception: ActividadDeportivaException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        } catch (NoExisteCuponeraException_Exception e) { 
            System.out.println("Expected exception: NoExisteCuponeraException has occurred.");
            System.out.println(e.toString());
        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sortearPremios...");
        java.lang.String _sortearPremios_arg0 = "_sortearPremios_arg078080045";
        java.lang.String _sortearPremios_arg1 = "_sortearPremios_arg1-1234106536";
        java.lang.String _sortearPremios_arg2 = "_sortearPremios_arg21571206649";
        try {
            net.java.dev.jaxb.array.StringArray _sortearPremios__return = port.sortearPremios(_sortearPremios_arg0, _sortearPremios_arg1, _sortearPremios_arg2);
            System.out.println("sortearPremios.result=" + _sortearPremios__return);

        } catch (ClaseException_Exception e) { 
            System.out.println("Expected exception: ClaseException has occurred.");
            System.out.println(e.toString());
        } catch (ActividadDeportivaException_Exception e) { 
            System.out.println("Expected exception: ActividadDeportivaException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
