package webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-06T19:16:01.871-03:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://webServices/", name = "WSClaseController")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WSClaseController {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public java.lang.String obtenerInstitucionActDep(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public DtClaseWS seleccionarClase(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2
    ) throws ClaseException_Exception, ActividadDeportivaException_Exception, InstitucionException_Exception;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray obtenerActividades(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws InstitucionException_Exception;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray getCuponerasSocioClase(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray obtenerClases(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    ) throws InstitucionException_Exception;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray obtenerActividadesAprobadas(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws InstitucionException_Exception;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray obtenerUsuarios();

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public DtClaseWS buscarClase(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws ClaseException_Exception;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray obtenerSocios();

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray obtenerProfesores(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws InstitucionException_Exception;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray obtenerInstituciones();

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray getCuponerasDisponibles(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2
    ) throws UsuarioNoExisteException_Exception, ActividadDeportivaException_Exception, InstitucionException_Exception;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public int ingresarDatosClase(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        DtClaseWS arg2
    ) throws UsuarioNoExisteException_Exception, FechaInvalidaException_Exception, ClaseException_Exception, ActividadDeportivaException_Exception, InstitucionException_Exception;

    @WebMethod
    public void inscribirSocio(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3,
        @WebParam(partName = "arg4", name = "arg4")
        TRegWS arg4,
        @WebParam(partName = "arg5", name = "arg5")
        DtFechaWS arg5,
        @WebParam(partName = "arg6", name = "arg6")
        java.lang.String arg6
    ) throws ClaseException_Exception, FechaInvalidaException_Exception, ActividadDeportivaException_Exception, InstitucionException_Exception, NoExisteCuponeraException_Exception, UsuarioNoExisteException_Exception;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public net.java.dev.jaxb.array.StringArray sortearPremios(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2
    ) throws ClaseException_Exception, ActividadDeportivaException_Exception, InstitucionException_Exception;
}
