package webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-12T11:03:36.044-03:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://webServices/", name = "WSContentController")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WSContentController {

    @WebMethod
    public void sendReports(
        @WebParam(partName = "arg0", name = "arg0")
        LogEntryWSArray arg0
    );

//	@WebMethod
    public void sendReports(
        @WebParam(partName = "arg0", name = "arg0")
        net.java.dev.jaxb.array.StringArray arg0
    );

	@WebMethod
    public void post(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        byte[] arg2
    ) throws IOException_Exception;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webServices/", partName = "return")
    public byte[] get(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    ) throws IOException_Exception;
}
