
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-08T01:00:08.192-03:00
 * Generated source version: 2.7.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSContentControllerService",
                      portName = "WSContentControllerPort",
                      targetNamespace = "http://webServices/",
                      wsdlLocation = "http://localhost:9129/entrenamosuy/contentController?wsdl",
                      endpointInterface = "webservices.WSContentController")
                      
public class WSContentControllerImpl implements WSContentController {

    private static final Logger LOG = Logger.getLogger(WSContentControllerImpl.class.getName());

    /* (non-Javadoc)
     * @see webservices.WSContentController#post(java.lang.String  arg0 ,)java.lang.String  arg1 ,)byte[]  arg2 )*
     */
    public void post(java.lang.String arg0,java.lang.String arg1,byte[] arg2) throws IOException_Exception    { 
        LOG.info("Executing operation post");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IOException_Exception("IOException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSContentController#get(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public byte[] get(java.lang.String arg0,java.lang.String arg1) throws IOException_Exception    { 
        LOG.info("Executing operation get");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            byte[] _return = new byte[] {};
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IOException_Exception("IOException...");
    }

}
