package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-06T19:16:24.185-03:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "WSCuponeraControllerService", 
                  wsdlLocation = "http://localhost:9129/entrenamosuy/cuponeraController?wsdl",
                  targetNamespace = "http://webServices/") 
public class WSCuponeraControllerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webServices/", "WSCuponeraControllerService");
    public final static QName WSCuponeraControllerPort = new QName("http://webServices/", "WSCuponeraControllerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9129/entrenamosuy/cuponeraController?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSCuponeraControllerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9129/entrenamosuy/cuponeraController?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSCuponeraControllerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSCuponeraControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCuponeraControllerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSCuponeraControllerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSCuponeraControllerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSCuponeraControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSCuponeraController
     */
    @WebEndpoint(name = "WSCuponeraControllerPort")
    public WSCuponeraController getWSCuponeraControllerPort() {
        return super.getPort(WSCuponeraControllerPort, WSCuponeraController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCuponeraController
     */
    @WebEndpoint(name = "WSCuponeraControllerPort")
    public WSCuponeraController getWSCuponeraControllerPort(WebServiceFeature... features) {
        return super.getPort(WSCuponeraControllerPort, WSCuponeraController.class, features);
    }

}
