
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package webservices;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-07T14:12:53.942-03:00
 * Generated source version: 2.7.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSCuponeraControllerService",
                      portName = "WSCuponeraControllerPort",
                      targetNamespace = "http://webServices/",
                      wsdlLocation = "http://localhost:9129/entrenamosuy/cuponeraController?wsdl",
                      endpointInterface = "webservices.WSCuponeraController")
                      
public class WSCuponeraControllerImpl implements WSCuponeraController {

    private static final Logger LOG = Logger.getLogger(WSCuponeraControllerImpl.class.getName());

    /* (non-Javadoc)
     * @see webservices.WSCuponeraController#seleccionarCuponera(java.lang.String  arg0 )*
     */
    public webservices.DtCuponeraWS seleccionarCuponera(java.lang.String arg0) throws NoExisteCuponeraException_Exception    { 
        LOG.info("Executing operation seleccionarCuponera");
        System.out.println(arg0);
        try {
            webservices.DtCuponeraWS _return = new webservices.DtCuponeraWS();
            java.util.List<java.lang.String> _returnCategorias = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCategoriasVal1 = "_returnCategoriasVal-1503309793";
            _returnCategorias.add(_returnCategoriasVal1);
            _return.getCategorias().addAll(_returnCategorias);
            java.util.List<webservices.DtClasesCuponeraWS> _returnContenido = new java.util.ArrayList<webservices.DtClasesCuponeraWS>();
            webservices.DtClasesCuponeraWS _returnContenidoVal1 = new webservices.DtClasesCuponeraWS();
            _returnContenidoVal1.setCantidadClases(2001205250);
            _returnContenidoVal1.setNombreActividad("NombreActividad1881900516");
            _returnContenido.add(_returnContenidoVal1);
            _return.getContenido().addAll(_returnContenido);
            _return.setCosto(0.51511264f);
            _return.setDescripcion("Descripcion534720130");
            _return.setDescuento(0.31171286f);
            webservices.DtFechaWS _returnFechaAlta = new webservices.DtFechaWS();
            _returnFechaAlta.setAnio(795864702);
            _returnFechaAlta.setMes(1891849434);
            _returnFechaAlta.setDia(-1844142211);
            _returnFechaAlta.setHoras(-1936863790);
            _returnFechaAlta.setMinutos(-1529371450);
            _returnFechaAlta.setSegundos(392104037);
            _return.setFechaAlta(_returnFechaAlta);
            webservices.DtFechaWS _returnFechaFin = new webservices.DtFechaWS();
            _returnFechaFin.setAnio(924759117);
            _returnFechaFin.setMes(-209835344);
            _returnFechaFin.setDia(1908579397);
            _returnFechaFin.setHoras(1227024811);
            _returnFechaFin.setMinutos(2146640011);
            _returnFechaFin.setSegundos(-302143462);
            _return.setFechaFin(_returnFechaFin);
            webservices.DtFechaWS _returnFechaInicio = new webservices.DtFechaWS();
            _returnFechaInicio.setAnio(1637806191);
            _returnFechaInicio.setMes(1134396183);
            _returnFechaInicio.setDia(1960656030);
            _returnFechaInicio.setHoras(797232215);
            _returnFechaInicio.setMinutos(824405563);
            _returnFechaInicio.setSegundos(1215435424);
            _return.setFechaInicio(_returnFechaInicio);
            _return.setImg("Img1566587761");
            _return.setNombre("Nombre119870220");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoExisteCuponeraException_Exception("NoExisteCuponeraException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSCuponeraController#getNombreCuponeras(*
     */
    public net.java.dev.jaxb.array.StringArray getNombreCuponeras() { 
        LOG.info("Executing operation getNombreCuponeras");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-206527754";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSCuponeraController#getNombreCuponerasSinRecibos(*
     */
    public net.java.dev.jaxb.array.StringArray getNombreCuponerasSinRecibos() { 
        LOG.info("Executing operation getNombreCuponerasSinRecibos");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal2121159174";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
