
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-06T19:16:24.173-03:00
 * Generated source version: 2.7.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSCuponeraControllerService",
                      portName = "WSCuponeraControllerPort",
                      targetNamespace = "http://webServices/",
                      wsdlLocation = "http://localhost:9129/entrenamosuy/cuponeraController?wsdl",
                      endpointInterface = "webservices.WSCuponeraController")
                      
public class WSCuponeraControllerImpl implements WSCuponeraController {

    private static final Logger LOG = Logger.getLogger(WSCuponeraControllerImpl.class.getName());

    /* (non-Javadoc)
     * @see webservices.WSCuponeraController#seleccionarCuponera(java.lang.String  arg0 )*
     */
    public webservices.DtCuponeraWS seleccionarCuponera(java.lang.String arg0) throws NoExisteCuponeraException_Exception    { 
        LOG.info("Executing operation seleccionarCuponera");
        System.out.println(arg0);
        try {
            webservices.DtCuponeraWS _return = new webservices.DtCuponeraWS();
            java.util.List<java.lang.String> _returnCategorias = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCategoriasVal1 = "_returnCategoriasVal-2091821053";
            _returnCategorias.add(_returnCategoriasVal1);
            _return.getCategorias().addAll(_returnCategorias);
            java.util.List<webservices.DtClasesCuponeraWS> _returnContenido = new java.util.ArrayList<webservices.DtClasesCuponeraWS>();
            webservices.DtClasesCuponeraWS _returnContenidoVal1 = new webservices.DtClasesCuponeraWS();
            _returnContenidoVal1.setCantidadClases(-441764317);
            _returnContenidoVal1.setNombreActividad("NombreActividad-313027175");
            _returnContenido.add(_returnContenidoVal1);
            _return.getContenido().addAll(_returnContenido);
            _return.setCosto(0.2332437f);
            _return.setDescripcion("Descripcion-120941640");
            _return.setDescuento(0.64390826f);
            webservices.DtFechaWS _returnFechaAlta = new webservices.DtFechaWS();
            _returnFechaAlta.setAnio(171588489);
            _returnFechaAlta.setMes(389274333);
            _returnFechaAlta.setDia(-1258617369);
            _returnFechaAlta.setHoras(1951735625);
            _returnFechaAlta.setMinutos(-85937522);
            _returnFechaAlta.setSegundos(50066995);
            _return.setFechaAlta(_returnFechaAlta);
            webservices.DtFechaWS _returnFechaFin = new webservices.DtFechaWS();
            _returnFechaFin.setAnio(-915963860);
            _returnFechaFin.setMes(-753102007);
            _returnFechaFin.setDia(236490177);
            _returnFechaFin.setHoras(1961886117);
            _returnFechaFin.setMinutos(145741106);
            _returnFechaFin.setSegundos(791098929);
            _return.setFechaFin(_returnFechaFin);
            webservices.DtFechaWS _returnFechaInicio = new webservices.DtFechaWS();
            _returnFechaInicio.setAnio(-209360899);
            _returnFechaInicio.setMes(1689369917);
            _returnFechaInicio.setDia(587371113);
            _returnFechaInicio.setHoras(1165927902);
            _returnFechaInicio.setMinutos(534320817);
            _returnFechaInicio.setSegundos(682291727);
            _return.setFechaInicio(_returnFechaInicio);
            _return.setImg("Img312877301");
            _return.setNombre("Nombre-2060799826");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoExisteCuponeraException_Exception("NoExisteCuponeraException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSCuponeraController#getNombreCuponeras(*
     */
    public net.java.dev.jaxb.array.StringArray getNombreCuponeras() { 
        LOG.info("Executing operation getNombreCuponeras");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1747208714";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSCuponeraController#getNombreCuponerasSinRecibos(*
     */
    public net.java.dev.jaxb.array.StringArray getNombreCuponerasSinRecibos() { 
        LOG.info("Executing operation getNombreCuponerasSinRecibos");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1648062783";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
