
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package webservices;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-09T11:33:16.467-03:00
 * Generated source version: 2.7.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSUsuarioControllerService",
                      portName = "WSUsuarioControllerPort",
                      targetNamespace = "http://webServices/",
                      endpointInterface = "webservices.WSUsuarioController")
                      
public class WSUsuarioControllerImpl implements WSUsuarioController {

    private static final Logger LOG = Logger.getLogger(WSUsuarioControllerImpl.class.getName());

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#dejarDeSeguir(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public void dejarDeSeguir(java.lang.String arg0,java.lang.String arg1) throws UsuarioNoExisteException_Exception    { 
        LOG.info("Executing operation dejarDeSeguir");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#ingresarDatosUsuario(webservices.DtUsuarioWS  arg0 )*
     */
    public int ingresarDatosUsuario(DtUsuarioWS arg0) throws InstitucionException_Exception    { 
        LOG.info("Executing operation ingresarDatosUsuario");
        System.out.println(arg0);
        try {
            int _return = -636066602;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#seleccionarUsuario(java.lang.String  arg0 )*
     */
    public webservices.DtUsuarioWS seleccionarUsuario(java.lang.String arg0) throws UsuarioNoExisteException_Exception    { 
        LOG.info("Executing operation seleccionarUsuario");
        System.out.println(arg0);
        try {
            webservices.DtUsuarioWS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#verificarIdentidadNickname(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public boolean verificarIdentidadNickname(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation verificarIdentidadNickname");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#comprarCuponera(java.lang.String  arg0 ,)java.lang.String  arg1 ,)webservices.DtFechaWS  arg2 )*
     */
    public void comprarCuponera(java.lang.String arg0,java.lang.String arg1,DtFechaWS arg2) throws UsuarioNoExisteException_Exception , CuponeraNoExisteException_Exception    { 
        LOG.info("Executing operation comprarCuponera");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
        //throw new CuponeraNoExisteException_Exception("CuponeraNoExisteException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#seleccionarSocio(java.lang.String  arg0 )*
     */
    public webservices.DtSocioWS seleccionarSocio(java.lang.String arg0) throws UsuarioNoExisteException_Exception    { 
        LOG.info("Executing operation seleccionarSocio");
        System.out.println(arg0);
        try {
            webservices.DtSocioWS _return = new webservices.DtSocioWS();
            _return.setNickname("Nickname-593137463");
            _return.setNombre("Nombre644301742");
            _return.setApellido("Apellido804237278");
            _return.setEmail("Email805755326");
            _return.setContrasenia("Contrasenia201478036");
            webservices.DtFechaWS _returnFechaNacimiento = new webservices.DtFechaWS();
            _returnFechaNacimiento.setAnio(-1633287415);
            _returnFechaNacimiento.setMes(-1649661417);
            _returnFechaNacimiento.setDia(1234902206);
            _returnFechaNacimiento.setHoras(14557447);
            _returnFechaNacimiento.setMinutos(-1074260160);
            _returnFechaNacimiento.setSegundos(732443960);
            _return.setFechaNacimiento(_returnFechaNacimiento);
            byte[] _returnImagen = new byte[] {};
            _return.setImagen(_returnImagen);
            java.util.List<java.lang.String> _returnSeguidosNickname = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnSeguidosNicknameVal1 = "_returnSeguidosNicknameVal480764638";
            _returnSeguidosNickname.add(_returnSeguidosNicknameVal1);
            _return.getSeguidosNickname().addAll(_returnSeguidosNickname);
            java.util.List<java.lang.String> _returnSeguidoresNickname = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnSeguidoresNicknameVal1 = "_returnSeguidoresNicknameVal-926830357";
            _returnSeguidoresNickname.add(_returnSeguidoresNicknameVal1);
            _return.getSeguidoresNickname().addAll(_returnSeguidoresNickname);
            java.util.List<java.lang.String> _returnClasesDeActividadesHead = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnClasesDeActividadesHeadVal1 = "_returnClasesDeActividadesHeadVal1016793532";
            _returnClasesDeActividadesHead.add(_returnClasesDeActividadesHeadVal1);
            _return.getClasesDeActividadesHead().addAll(_returnClasesDeActividadesHead);
            java.util.List<net.java.dev.jaxb.array.StringArray> _returnClasesDeActividadesData = new java.util.ArrayList<net.java.dev.jaxb.array.StringArray>();
            net.java.dev.jaxb.array.StringArray _returnClasesDeActividadesDataVal1 = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnClasesDeActividadesDataVal1Item = new java.util.ArrayList<java.lang.String>();
            _returnClasesDeActividadesDataVal1.getItem().addAll(_returnClasesDeActividadesDataVal1Item);
            _returnClasesDeActividadesData.add(_returnClasesDeActividadesDataVal1);
            _return.getClasesDeActividadesData().addAll(_returnClasesDeActividadesData);
            java.util.List<java.lang.String> _returnClasesDeActividadesFinalizadasHead = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnClasesDeActividadesFinalizadasHeadVal1 = "_returnClasesDeActividadesFinalizadasHeadVal-1816868526";
            _returnClasesDeActividadesFinalizadasHead.add(_returnClasesDeActividadesFinalizadasHeadVal1);
            _return.getClasesDeActividadesFinalizadasHead().addAll(_returnClasesDeActividadesFinalizadasHead);
            java.util.List<net.java.dev.jaxb.array.StringArray> _returnClasesDeActividadesFinalizadasData = new java.util.ArrayList<net.java.dev.jaxb.array.StringArray>();
            net.java.dev.jaxb.array.StringArray _returnClasesDeActividadesFinalizadasDataVal1 = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnClasesDeActividadesFinalizadasDataVal1Item = new java.util.ArrayList<java.lang.String>();
            _returnClasesDeActividadesFinalizadasDataVal1.getItem().addAll(_returnClasesDeActividadesFinalizadasDataVal1Item);
            _returnClasesDeActividadesFinalizadasData.add(_returnClasesDeActividadesFinalizadasDataVal1);
            _return.getClasesDeActividadesFinalizadasData().addAll(_returnClasesDeActividadesFinalizadasData);
            java.util.List<java.lang.String> _returnCuponerasCompradas = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCuponerasCompradasVal1 = "_returnCuponerasCompradasVal-833482719";
            _returnCuponerasCompradas.add(_returnCuponerasCompradasVal1);
            _return.getCuponerasCompradas().addAll(_returnCuponerasCompradas);
            java.util.List<java.lang.String> _returnActividadesFavoritas = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnActividadesFavoritasVal1 = "_returnActividadesFavoritasVal-2120295083";
            _returnActividadesFavoritas.add(_returnActividadesFavoritasVal1);
            _return.getActividadesFavoritas().addAll(_returnActividadesFavoritas);
            java.util.List<java.lang.String> _returnPremiosHead = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnPremiosHeadVal1 = "_returnPremiosHeadVal-889324398";
            _returnPremiosHead.add(_returnPremiosHeadVal1);
            _return.getPremiosHead().addAll(_returnPremiosHead);
            java.util.List<webservices.DtPremioWS> _returnPremiosData = new java.util.ArrayList<webservices.DtPremioWS>();
            webservices.DtPremioWS _returnPremiosDataVal1 = new webservices.DtPremioWS();
            _returnPremiosDataVal1.setDescripcion("Descripcion-1041614081");
            _returnPremiosDataVal1.setCantidad(1529154388);
            webservices.DtFechaWS _returnPremiosDataVal1FechaSorteo = new webservices.DtFechaWS();
            _returnPremiosDataVal1FechaSorteo.setAnio(1333914101);
            _returnPremiosDataVal1FechaSorteo.setMes(-1131438769);
            _returnPremiosDataVal1FechaSorteo.setDia(-685461285);
            _returnPremiosDataVal1FechaSorteo.setHoras(1451686002);
            _returnPremiosDataVal1FechaSorteo.setMinutos(-642501461);
            _returnPremiosDataVal1FechaSorteo.setSegundos(1144127480);
            _returnPremiosDataVal1.setFechaSorteo(_returnPremiosDataVal1FechaSorteo);
            java.util.List<java.lang.String> _returnPremiosDataVal1Ganadores = new java.util.ArrayList<java.lang.String>();
            _returnPremiosDataVal1.getGanadores().addAll(_returnPremiosDataVal1Ganadores);
            _returnPremiosData.add(_returnPremiosDataVal1);
            _return.getPremiosData().addAll(_returnPremiosData);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#valorarProfesor(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)int  arg4 )*
     */
    public void valorarProfesor(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,int arg4) throws UsuarioNoExisteException_Exception , ClaseException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation valorarProfesor");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
        //throw new ClaseException_Exception("ClaseException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#favoritearActividad(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public void favoritearActividad(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) throws UsuarioNoExisteException_Exception , InstitucionException_Exception    { 
        LOG.info("Executing operation favoritearActividad");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
        //throw new InstitucionException_Exception("InstitucionException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#obtenerUsuarios(*
     */
    public webservices.DtCapsula obtenerUsuarios() { 
        LOG.info("Executing operation obtenerUsuarios");
        try {
            webservices.DtCapsula _return = new webservices.DtCapsula();
            java.lang.Object _returnContenido = null;
            _return.setContenido(_returnContenido);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#seleccionarProfesor(java.lang.String  arg0 )*
     */
    public webservices.DtProfesorWS seleccionarProfesor(java.lang.String arg0) throws UsuarioNoExisteException_Exception    { 
        LOG.info("Executing operation seleccionarProfesor");
        System.out.println(arg0);
        try {
            webservices.DtProfesorWS _return = new webservices.DtProfesorWS();
            _return.setNickname("Nickname-1630667725");
            _return.setNombre("Nombre1212921161");
            _return.setApellido("Apellido1350377311");
            _return.setEmail("Email-1562204596");
            _return.setContrasenia("Contrasenia866109692");
            webservices.DtFechaWS _returnFechaNacimiento = new webservices.DtFechaWS();
            _returnFechaNacimiento.setAnio(392723548);
            _returnFechaNacimiento.setMes(572998417);
            _returnFechaNacimiento.setDia(1430599499);
            _returnFechaNacimiento.setHoras(-1438361338);
            _returnFechaNacimiento.setMinutos(-997961205);
            _returnFechaNacimiento.setSegundos(29179950);
            _return.setFechaNacimiento(_returnFechaNacimiento);
            byte[] _returnImagen = new byte[] {};
            _return.setImagen(_returnImagen);
            java.util.List<java.lang.String> _returnSeguidosNickname = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnSeguidosNicknameVal1 = "_returnSeguidosNicknameVal2057546491";
            _returnSeguidosNickname.add(_returnSeguidosNicknameVal1);
            _return.getSeguidosNickname().addAll(_returnSeguidosNickname);
            java.util.List<java.lang.String> _returnSeguidoresNickname = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnSeguidoresNicknameVal1 = "_returnSeguidoresNicknameVal1684749937";
            _returnSeguidoresNickname.add(_returnSeguidoresNicknameVal1);
            _return.getSeguidoresNickname().addAll(_returnSeguidoresNickname);
            java.util.List<java.lang.String> _returnHistoralActDepIngresadasNombre = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnHistoralActDepIngresadasNombreVal1 = "_returnHistoralActDepIngresadasNombreVal-465592335";
            _returnHistoralActDepIngresadasNombre.add(_returnHistoralActDepIngresadasNombreVal1);
            _return.getHistoralActDepIngresadasNombre().addAll(_returnHistoralActDepIngresadasNombre);
            java.util.List<webservices.TEstadoWS> _returnHistoralActDepIngresadasEstado = new java.util.ArrayList<webservices.TEstadoWS>();
            webservices.TEstadoWS _returnHistoralActDepIngresadasEstadoVal1 = webservices.TEstadoWS.ACEPTADA;
            _returnHistoralActDepIngresadasEstado.add(_returnHistoralActDepIngresadasEstadoVal1);
            _return.getHistoralActDepIngresadasEstado().addAll(_returnHistoralActDepIngresadasEstado);
            java.util.List<java.lang.String> _returnActDepAsociadasHead = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnActDepAsociadasHeadVal1 = "_returnActDepAsociadasHeadVal1574891113";
            _returnActDepAsociadasHead.add(_returnActDepAsociadasHeadVal1);
            _return.getActDepAsociadasHead().addAll(_returnActDepAsociadasHead);
            java.util.List<net.java.dev.jaxb.array.StringArray> _returnActDepAsociadasData = new java.util.ArrayList<net.java.dev.jaxb.array.StringArray>();
            net.java.dev.jaxb.array.StringArray _returnActDepAsociadasDataVal1 = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnActDepAsociadasDataVal1Item = new java.util.ArrayList<java.lang.String>();
            _returnActDepAsociadasDataVal1.getItem().addAll(_returnActDepAsociadasDataVal1Item);
            _returnActDepAsociadasData.add(_returnActDepAsociadasDataVal1);
            _return.getActDepAsociadasData().addAll(_returnActDepAsociadasData);
            _return.setNombreInstitucion("NombreInstitucion1045088607");
            _return.setDescripcion("Descripcion-2117098867");
            _return.setBiografia("Biografia1373862970");
            _return.setLink("Link-420002835");
            _return.setValoracion(0.13620162f);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#ping(*
     */
    public java.lang.String ping() { 
        LOG.info("Executing operation ping");
        try {
            java.lang.String _return = "_return-315585245";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#verificarIdentidadEmail(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public boolean verificarIdentidadEmail(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation verificarIdentidadEmail");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#seleccionarUsuarioEmail(java.lang.String  arg0 )*
     */
    public webservices.DtUsuarioWS seleccionarUsuarioEmail(java.lang.String arg0) throws UsuarioNoExisteException_Exception    { 
        LOG.info("Executing operation seleccionarUsuarioEmail");
        System.out.println(arg0);
        try {
            webservices.DtUsuarioWS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#obtenerInstituciones(*
     */
    public webservices.DtCapsula obtenerInstituciones() { 
        LOG.info("Executing operation obtenerInstituciones");
        try {
            webservices.DtCapsula _return = new webservices.DtCapsula();
            java.lang.Object _returnContenido = null;
            _return.setContenido(_returnContenido);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#seguir(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public void seguir(java.lang.String arg0,java.lang.String arg1) throws UsuarioNoExisteException_Exception    { 
        LOG.info("Executing operation seguir");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

    /* (non-Javadoc)
     * @see webservices.WSUsuarioController#editarDatosBasicos(java.lang.String  arg0 ,)webservices.DtUsuarioWS  arg1 )*
     */
    public void editarDatosBasicos(java.lang.String arg0,DtUsuarioWS arg1) throws UsuarioNoExisteException_Exception    { 
        LOG.info("Executing operation editarDatosBasicos");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

}
