package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import servlets.ConfigListener;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-09T11:33:16.492-03:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "WSUsuarioControllerService", 
                
                  targetNamespace = "http://webServices/") 
public class WSUsuarioControllerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webServices/", "WSUsuarioControllerService");
    public final static QName WSUsuarioControllerPort = new QName("http://webServices/", "WSUsuarioControllerPort");
    static {
        URL url = null;
        try {
            url = new URL(ConfigListener.cfg.getProperty("usuarioControllerURL"));
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSUsuarioControllerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", ConfigListener.cfg.getProperty("usuarioControllerURL"));
        }
        WSDL_LOCATION = url;
    }

    public WSUsuarioControllerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSUsuarioControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSUsuarioControllerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSUsuarioControllerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSUsuarioControllerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSUsuarioControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSUsuarioController
     */
    @WebEndpoint(name = "WSUsuarioControllerPort")
    public WSUsuarioController getWSUsuarioControllerPort() {
        return super.getPort(WSUsuarioControllerPort, WSUsuarioController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSUsuarioController
     */
    @WebEndpoint(name = "WSUsuarioControllerPort")
    public WSUsuarioController getWSUsuarioControllerPort(WebServiceFeature... features) {
        return super.getPort(WSUsuarioControllerPort, WSUsuarioController.class, features);
    }

}
