
package webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-11-09T11:33:16.370-03:00
 * Generated source version: 2.7.9
 * 
 */
public final class WSUsuarioController_WSUsuarioControllerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webServices/", "WSUsuarioControllerService");

    private WSUsuarioController_WSUsuarioControllerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSUsuarioControllerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSUsuarioControllerService ss = new WSUsuarioControllerService(wsdlURL, SERVICE_NAME);
        WSUsuarioController port = ss.getWSUsuarioControllerPort();  
        
        {
        System.out.println("Invoking dejarDeSeguir...");
        java.lang.String _dejarDeSeguir_arg0 = "_dejarDeSeguir_arg01742373186";
        java.lang.String _dejarDeSeguir_arg1 = "_dejarDeSeguir_arg1-1350972166";
        try {
            port.dejarDeSeguir(_dejarDeSeguir_arg0, _dejarDeSeguir_arg1);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking ingresarDatosUsuario...");
        webservices.DtUsuarioWS _ingresarDatosUsuario_arg0 = null;
        try {
            int _ingresarDatosUsuario__return = port.ingresarDatosUsuario(_ingresarDatosUsuario_arg0);
            System.out.println("ingresarDatosUsuario.result=" + _ingresarDatosUsuario__return);

        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking seleccionarUsuario...");
        java.lang.String _seleccionarUsuario_arg0 = "_seleccionarUsuario_arg0-899122896";
        try {
            webservices.DtUsuarioWS _seleccionarUsuario__return = port.seleccionarUsuario(_seleccionarUsuario_arg0);
            System.out.println("seleccionarUsuario.result=" + _seleccionarUsuario__return);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking verificarIdentidadNickname...");
        java.lang.String _verificarIdentidadNickname_arg0 = "_verificarIdentidadNickname_arg01309890282";
        java.lang.String _verificarIdentidadNickname_arg1 = "_verificarIdentidadNickname_arg11277989961";
        boolean _verificarIdentidadNickname__return = port.verificarIdentidadNickname(_verificarIdentidadNickname_arg0, _verificarIdentidadNickname_arg1);
        System.out.println("verificarIdentidadNickname.result=" + _verificarIdentidadNickname__return);


        }
        {
        System.out.println("Invoking comprarCuponera...");
        java.lang.String _comprarCuponera_arg0 = "_comprarCuponera_arg0-1549587859";
        java.lang.String _comprarCuponera_arg1 = "_comprarCuponera_arg1-428604492";
        webservices.DtFechaWS _comprarCuponera_arg2 = new webservices.DtFechaWS();
        _comprarCuponera_arg2.setAnio(-462100851);
        _comprarCuponera_arg2.setMes(522018907);
        _comprarCuponera_arg2.setDia(-237085186);
        _comprarCuponera_arg2.setHoras(992083281);
        _comprarCuponera_arg2.setMinutos(-1219187385);
        _comprarCuponera_arg2.setSegundos(1207736046);
        try {
            port.comprarCuponera(_comprarCuponera_arg0, _comprarCuponera_arg1, _comprarCuponera_arg2);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        } catch (CuponeraNoExisteException_Exception e) { 
            System.out.println("Expected exception: CuponeraNoExisteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking seleccionarSocio...");
        java.lang.String _seleccionarSocio_arg0 = "_seleccionarSocio_arg0-845413965";
        try {
            webservices.DtSocioWS _seleccionarSocio__return = port.seleccionarSocio(_seleccionarSocio_arg0);
            System.out.println("seleccionarSocio.result=" + _seleccionarSocio__return);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking valorarProfesor...");
        java.lang.String _valorarProfesor_arg0 = "_valorarProfesor_arg0-992328758";
        java.lang.String _valorarProfesor_arg1 = "_valorarProfesor_arg1-1213099248";
        java.lang.String _valorarProfesor_arg2 = "_valorarProfesor_arg2-1531759353";
        java.lang.String _valorarProfesor_arg3 = "_valorarProfesor_arg3-1544522370";
        int _valorarProfesor_arg4 = -454011513;
        try {
            port.valorarProfesor(_valorarProfesor_arg0, _valorarProfesor_arg1, _valorarProfesor_arg2, _valorarProfesor_arg3, _valorarProfesor_arg4);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        } catch (ClaseException_Exception e) { 
            System.out.println("Expected exception: ClaseException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking favoritearActividad...");
        java.lang.String _favoritearActividad_arg0 = "_favoritearActividad_arg0-2119574049";
        java.lang.String _favoritearActividad_arg1 = "_favoritearActividad_arg1-1595030529";
        java.lang.String _favoritearActividad_arg2 = "_favoritearActividad_arg2-1687057746";
        try {
            port.favoritearActividad(_favoritearActividad_arg0, _favoritearActividad_arg1, _favoritearActividad_arg2);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        } catch (InstitucionException_Exception e) { 
            System.out.println("Expected exception: InstitucionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerUsuarios...");
        webservices.DtCapsula _obtenerUsuarios__return = port.obtenerUsuarios();
        System.out.println("obtenerUsuarios.result=" + _obtenerUsuarios__return);


        }
        {
        System.out.println("Invoking seleccionarProfesor...");
        java.lang.String _seleccionarProfesor_arg0 = "_seleccionarProfesor_arg0-1577088508";
        try {
            webservices.DtProfesorWS _seleccionarProfesor__return = port.seleccionarProfesor(_seleccionarProfesor_arg0);
            System.out.println("seleccionarProfesor.result=" + _seleccionarProfesor__return);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking ping...");
        java.lang.String _ping__return = port.ping();
        System.out.println("ping.result=" + _ping__return);


        }
        {
        System.out.println("Invoking verificarIdentidadEmail...");
        java.lang.String _verificarIdentidadEmail_arg0 = "_verificarIdentidadEmail_arg01385761852";
        java.lang.String _verificarIdentidadEmail_arg1 = "_verificarIdentidadEmail_arg1-1415355766";
        boolean _verificarIdentidadEmail__return = port.verificarIdentidadEmail(_verificarIdentidadEmail_arg0, _verificarIdentidadEmail_arg1);
        System.out.println("verificarIdentidadEmail.result=" + _verificarIdentidadEmail__return);


        }
        {
        System.out.println("Invoking seleccionarUsuarioEmail...");
        java.lang.String _seleccionarUsuarioEmail_arg0 = "_seleccionarUsuarioEmail_arg0-1199639896";
        try {
            webservices.DtUsuarioWS _seleccionarUsuarioEmail__return = port.seleccionarUsuarioEmail(_seleccionarUsuarioEmail_arg0);
            System.out.println("seleccionarUsuarioEmail.result=" + _seleccionarUsuarioEmail__return);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerInstituciones...");
        webservices.DtCapsula _obtenerInstituciones__return = port.obtenerInstituciones();
        System.out.println("obtenerInstituciones.result=" + _obtenerInstituciones__return);


        }
        {
        System.out.println("Invoking seguir...");
        java.lang.String _seguir_arg0 = "_seguir_arg01411902572";
        java.lang.String _seguir_arg1 = "_seguir_arg1-761248494";
        try {
            port.seguir(_seguir_arg0, _seguir_arg1);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking editarDatosBasicos...");
        java.lang.String _editarDatosBasicos_arg0 = "_editarDatosBasicos_arg0-1978279435";
        webservices.DtUsuarioWS _editarDatosBasicos_arg1 = null;
        try {
            port.editarDatosBasicos(_editarDatosBasicos_arg0, _editarDatosBasicos_arg1);

        } catch (UsuarioNoExisteException_Exception e) { 
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
