/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-11 02:55:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import servlets.Login;
import datatypes.DtUsuarioExt;
import datatypes.DtProfesorExt;
import java.util.Set;

public final class stdLeftSection_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 @SuppressWarnings("unchecked") 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("servlets.Login");
    _jspx_imports_classes.add("datatypes.DtUsuarioExt");
    _jspx_imports_classes.add("datatypes.DtProfesorExt");
    _jspx_imports_classes.add("java.util.Set");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 
DtUsuarioExt u = (DtUsuarioExt)request.getSession().getAttribute("loggedUser");
if (u!=null){
	
      out.write("\r\n");
      out.write("	<nav style=\"margin-bottom: 3em;\" class=\"extraInfoDiv ins-cat-section nav flex-column\">\r\n");
      out.write("	<h1 class=\"fs-5\">Acciones</h1>\r\n");
      out.write("       <button type=\"button\" id=\"btn-myUser\" class=\"btn btn-link\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/usuarios?nickname=");
      out.print(u.getNickname());
      out.write("'\">\r\n");
      out.write("        	Ir a mi perfil\r\n");
      out.write("    	</button>\r\n");
      out.write("	");
 if (u instanceof DtProfesorExt){ 
      out.write("\r\n");
      out.write("	   <button type=\"button\" id=\"btn-altaActDep\" class=\"btn btn-link\" data-bs-toggle=\"modal\" data-bs-target=\"#altaActModal\">\r\n");
      out.write("            Alta Actividad Deportiva\r\n");
      out.write("      </button>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("      \r\n");
      out.write("	  </nav>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"extraInfoDiv ins-cat-section nav flex-column\">\r\n");
      out.write("  <h1 class=\"fs-5\">Instituciones</h1>\r\n");
      out.write("  ");

  Set<String> s = (Set<String>)request.getAttribute("stdInstituciones");
  for (String x: s){ 
      out.write("\r\n");
      out.write("  	<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/search?actividades=yes&cuponeras=yes&fltrI1=");
      out.print(x);
      out.write('"');
      out.write('>');
      out.print(x);
      out.write("</a>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<nav class=\"extraInfoDiv ins-cat-section nav flex-column mt-5\">\r\n");
      out.write("  <h1 class=\"fs-5\">Categorías</h1>\r\n");
      out.write("  ");

  Set<String> s2 = (Set<String>)request.getAttribute("stdCategorias");
  for (String x: s2){ 
      out.write("\r\n");
      out.write("  	<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/search?actividades=yes&cuponeras=yes&fltrC1=");
      out.print(x);
      out.write('"');
      out.write('>');
      out.print(x);
      out.write("</a>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("</nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
